/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Attachment, IceThicknessLayer, SnowDensity, SnowDensityLayer, SnowTempObs, StratProfileLayer, Url, WaterLevelMeasurement } from "./components/varsom-observasjon/observation-model";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface VarsomAttachment {
        "Aspect"?: any;
        "AttachmentId"?: any;
        "AttachmentMimeType"?: any;
        "Comment": any;
        "Copyright": any;
        "CropImage"?: boolean;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "IsMainAttachment"?: any;
        "Photographer": any;
        "RegistrationName": any;
        "RegistrationTID"?: any;
        "Url": any;
        "shortVersion": any;
        "strings"?: any;
    }
    interface VarsomAvalancheActivityObs {
        "Aspect": any;
        "Attachments": Attachment[];
        "AvalancheActivityObsID": any;
        "AvalancheName": any;
        "AvalancheTID": any;
        "AvalancheTriggerName": any;
        "AvalancheTriggerTID": any;
        "Comment": any;
        "DestructiveSizeName": any;
        "DestructiveSizeTID": any;
        "DtAvalancheTime": any;
        "DtOffAvalancheTime": any;
        "EstimatedNumName": any;
        "EstimatedNumTID": any;
        "HeigthStartZone": any;
        "SnowLine": any;
        "SnowLineName": any;
        "TerrainStartZoneName": any;
        "TerrainStartZoneTID": any;
        "header": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomAvalancheActivityObs2 {
        "Attachments": Attachment[];
        "AvalCauseName": any;
        "AvalCauseTID": any;
        "AvalPropagationName": any;
        "AvalPropagationTID": any;
        "AvalTriggerSimpleName": any;
        "AvalTriggerSimpleTID": any;
        "AvalancheExtName": any;
        "AvalancheExtTID": any;
        "Comment": any;
        "DestructiveSizeName": any;
        "DestructiveSizeTID": any;
        "DtEnd": any;
        "DtStart": any;
        "EstimatedNumName": any;
        "EstimatedNumTID": any;
        "ExposedHeight1": any;
        "ExposedHeight2": any;
        "ExposedHeightComboName": any;
        "ExposedHeightComboTID": any;
        "ValidExposition": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomAvalancheDangerObs {
        "Attachments": Attachment[];
        "AvalancheDangerObsID": any;
        "Comment": any;
        "DangerSignName": any;
        "DangerSignTID": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomAvalancheEvalProblem {
        "Attachments": Attachment[];
        "AvalCauseExtName": any;
        "AvalCauseExtTID": any;
        "AvalCauseName": any;
        "AvalCauseTID": any;
        "AvalProbabilityName": any;
        "AvalProbabilityTID": any;
        "AvalReleaseHeightName": any;
        "AvalReleaseHeightTID": any;
        "AvalTriggerSimpleName": any;
        "AvalTriggerSimpleTID": any;
        "AvalancheEvalProblemID": any;
        "AvalancheExtName": any;
        "AvalancheExtTID": any;
        "AvalancheProbabilityAutoText": any;
        "AvalancheProblemAutoText": any;
        "Comment": any;
        "DestructiveSizeExtName": any;
        "DestructiveSizeExtTID": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomAvalancheEvalProblem2 {
        "Attachments": Attachment[];
        "AvalCauseAttributeCrystalName": any;
        "AvalCauseAttributeCrystalTID": any;
        "AvalCauseAttributeLightName": any;
        "AvalCauseAttributeLightTID": any;
        "AvalCauseAttributeSoftName": any;
        "AvalCauseAttributeSoftTID": any;
        "AvalCauseAttributeThinName": any;
        "AvalCauseAttributeThinTID": any;
        "AvalCauseDepthName": any;
        "AvalCauseDepthTID": any;
        "AvalCauseName": any;
        "AvalCauseTID": any;
        "AvalProbabilityName": any;
        "AvalProbabilityTID": any;
        "AvalPropagationName": any;
        "AvalPropagationTID": any;
        "AvalTriggerSimpleName": any;
        "AvalTriggerSimpleTID": any;
        "AvalancheExtName": any;
        "AvalancheExtTID": any;
        "Comment": any;
        "DestructiveSizeName": any;
        "DestructiveSizeTID": any;
        "ExposedHeight1": any;
        "ExposedHeight2": any;
        "ExposedHeightComboName": any;
        "ExposedHeightComboTID": any;
        "ValidExposition": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomAvalancheEvaluation {
        "Attachments": Attachment[];
        "AvalancheDangerName": any;
        "AvalancheDangerTID": any;
        "AvalancheEvaluation1": any;
        "AvalancheProblemName1": any;
        "AvalancheProblemName2": any;
        "AvalancheProblemName3": any;
        "AvalancheProblemTID1": any;
        "AvalancheProblemTID2": any;
        "AvalancheProblemTID3": any;
        "CanPublish": any;
        "Comment": any;
        "RegID": any;
        "ValidExposition": any;
        "ValidHeightFrom": any;
        "ValidHeightRelative": any;
        "ValidHeigtTo": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomAvalancheEvaluation2 {
        "Attachments": Attachment[];
        "AvalancheDangerName": any;
        "AvalancheDangerTID": any;
        "AvalancheDevelopment": any;
        "AvalancheEvalProblems": any[];
        "AvalancheEvaluation": any;
        "Comment": any;
        "ExposedClimateName": any;
        "ExposedClimateTID": any;
        "ExposedHeight1": any;
        "ExposedHeight2": any;
        "ExposedHeightComboName": any;
        "ExposedHeightComboTID": any;
        "ValidExposition": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomAvalancheEvaluation3 {
        "Attachments": Attachment[];
        "AvalancheDangerName": any;
        "AvalancheDangerTID": any;
        "AvalancheDevelopment": any;
        "AvalancheEvaluation": any;
        "ForecastComment": any;
        "ForecastCorrectName": any;
        "ForecastCorrectTID": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomAvalancheObs {
        "Aspect": any;
        "Attachments": Attachment[];
        "AvalCauseName": any;
        "AvalCauseTID": any;
        "AvalancheName": any;
        "AvalancheTID": any;
        "AvalancheTriggerName": any;
        "AvalancheTriggerTID": any;
        "Comment": any;
        "DestructiveSizeName": any;
        "DestructiveSizeTID": any;
        "DtAvalancheTime": any;
        "FractureHeight": any;
        "FractureWidth": any;
        "HeightStartZone": any;
        "HeightStopZone": any;
        "RemotelyTriggered": any;
        "SnowLine": any;
        "StartLat": any;
        "StartLong": any;
        "StopLat": any;
        "StopLong": any;
        "TerrainStartZoneName": any;
        "TerrainStartZoneTID": any;
        "Trajectory": any;
        "ValidExposition": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomCompressionTest {
        "Attachments": Attachment[];
        "Comment": any;
        "ComprTestFractureName": any;
        "ComprTestFractureTID": any;
        "CompressionTestName": any;
        "CompressionTestTID": any;
        "FractureDepth": any;
        "IncludeInSnowProfile": any;
        "PropagationName": any;
        "PropagationTID": any;
        "PstX": any;
        "PstY": any;
        "RbRelease": any;
        "StabilityEvalName": any;
        "StabilityEvalTID": any;
        "TapsFracture": any;
        "TapsFullPropagation": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomDamageObs {
        "Attachments"?: Attachment[];
        "Comment": string;
        "DamagePosition": any;
        "DamageTypeName": string;
        "DamageTypeTID": number;
        "GeoHazardName": string;
        "GeoHazardTID": number;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomDangerObs {
        "Attachments": Attachment[];
        "Comment": any;
        "DangerSignName": any;
        "DangerSignTID": any;
        "GeoHazardName": any;
        "GeoHazardTID": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomDoc {
        "Text": any;
    }
    interface VarsomEstimateOfRisk {
        "comment": any;
        "dangerSignName": any;
        "strings": any;
    }
    interface VarsomGeneralObservation {
        "Attachments": Attachment[];
        "Comment": any;
        "GeoHazardName": any;
        "GeoHazardTID": any;
        "ObsComment": any;
        "ObsHeader": any;
        "Urls": Url[];
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomHeader {
        "regId": string;
        "region": string;
    }
    interface VarsomIceCoverObservation {
        "Attachments": Attachment[];
        "Comment": any;
        "IceCapacityName": any;
        "IceCapacityTID": any;
        "IceCoverAfterName": any;
        "IceCoverAfterTID": any;
        "IceCoverBeforeName": any;
        "IceCoverBeforeTID": any;
        "IceCoverName": any;
        "IceCoverTID": any;
        "IceSkateabilityName": any;
        "IceSkateabilityTID": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomIceThickness {
        "Attachments": Attachment[];
        "Comment": any;
        "DtObsTime": any;
        "HardCodedImg": any;
        "IceHeightAfter": any;
        "IceHeightBefore": any;
        "IceThicknessLayers": IceThicknessLayer[];
        "IceThicknessSum": any;
        "LocationName": any;
        "ObsLocationId": any;
        "SlushSnow": any;
        "SnowDepth": any;
        "regId": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomIceThicknessLayer {
        "Comment": any;
        "IceLayerName": any;
        "IceLayerThickness": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomImageSlider {
        "_images": any[];
        "shortVersion": string;
        "strings": any;
    }
    interface VarsomIncident {
        "ActivityInfluencedName": any;
        "ActivityInfluencedTID": any;
        "Attachments": Attachment[];
        "CasualtiesNum": any;
        "Comment": any;
        "DamageExtentName": any;
        "DamageExtentTID": any;
        "DeadNum": any;
        "DtEndTime": any;
        "EvacuatedNum": any;
        "ForecastAccurateName": any;
        "ForecastAccurateTID": any;
        "GeoHazardName": any;
        "GeoHazardTID": any;
        "HarmedNum": any;
        "IncidentHeader": any;
        "IncidentIngress": any;
        "IncidentText": any;
        "IncidentURLs": any[];
        "InvolvedNum": any;
        "LocalKnowledgeName": any;
        "LocalKnowledgeTID": any;
        "LocalTouristName": any;
        "LocalTouristTID": any;
        "MaterialDamages": any;
        "RescueName": any;
        "RescueTID": any;
        "SafetyGearName": any;
        "SafetyGearTID": any;
        "SlopeActivityName": any;
        "SlopeActivityTID": any;
        "TrafficObstructed": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomKeyValue {
        "_key": any;
        "_value"?: any;
        "shortVersion": string;
    }
    interface VarsomLabel {
        "label": any;
    }
    interface VarsomLabelSmall {
        "label": any;
    }
    interface VarsomLandslideObservation {
        "ActivityInfluencedName"?: any;
        "ActivityInfluencedTID"?: any;
        "Attachments": Attachment[];
        "Comment"?: any;
        "DamageExtentName"?: any;
        "DamageExtentTID"?: any;
        "DtLandSlideTime"?: any;
        "DtLandSlideTimeEnd"?: any;
        "ForecastAccurateName"?: any;
        "ForecastAccurateTID"?: any;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "LandSlideName"?: any;
        "LandSlideSizeName"?: any;
        "LandSlideSizeTID"?: any;
        "LandSlideTID"?: any;
        "LandSlideTriggerName"?: any;
        "LandSlideTriggerTID"?: any;
        "StartLat"?: any;
        "StartLong"?: any;
        "StopLat"?: any;
        "StopLong"?: any;
        "Urls"?: any[];
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomLatLng {
        "Latitude": any;
        "Longitude": any;
        "strings": any;
    }
    interface VarsomMetadata {
        "competenceLevelName": any;
        "dateOfLastUpdate"?: any;
        "dateOfRegistration": any;
        "geoHazardName": any;
        "moh": any;
        "nickname": any;
        "observerGroupName": any;
        "shortVersion": string;
        "strings"?: any;
    }
    interface VarsomObservation {
        "count": number;
        "json": any;
        "language": string;
        "number": number;
        "regid": string;
        "type": string;
        "version": string;
    }
    interface VarsomSignsOfDanger {
        "Comment"?: any;
        "Type"?: any;
        "strings"?: any;
    }
    interface VarsomSnowCoverObservation {
        "Attachments": Attachment[];
        "Comment": any;
        "CriticalLayerExists": any;
        "CriticalLayerLocation": any;
        "CriticalLayerName": any;
        "CriticalLayerTID": any;
        "DepthHoarThickness": any;
        "SnowPilotRef": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomSnowDensity {
        "Attachments": Attachment[];
        "Comment": any;
        "CylinderDiameter": any;
        "Layers": SnowDensityLayer[];
        "TareWeight": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomSnowDensityLayer {
        "Depth": any;
        "SortOrder": any;
        "Thickness": any;
        "WaterEquivalent": any;
        "Weight": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomSnowProfile {
        "Aspect": any;
        "Attachments": Attachment[];
        "Comment": any;
        "Copyright": any;
        "GeoHazardName": any;
        "GeoHazardTID": any;
        "Photographer": any;
        "RegistrationName": any;
        "RegistrationTID": any;
        "Url": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomSnowProfile2 {
        "Attachments": Attachment[];
        "Comment": any;
        "Exposition": any;
        "ImageUrl": any;
        "IsProfileToGround": any;
        "RegId": any;
        "SlopeAngle": any;
        "SnowDensity": SnowDensity[];
        "SnowTemp": any;
        "StratProfile": any;
        "TotalDepth": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomSnowSurfaceObservation {
        "Attachments": Attachment[];
        "Comment": any;
        "FootPenetration": any;
        "HeightLimitLayeredSnow": any;
        "NewSnowDepth24": any;
        "NewSnowLine": any;
        "SkiConditionsName": any;
        "SkiConditionsTID": any;
        "SnowDepth": any;
        "SnowDriftName": any;
        "SnowDriftTID": any;
        "SnowLine": any;
        "SnowSurfaceName": any;
        "SnowSurfaceTID": any;
        "SurfaceRoughnessName": any;
        "SurfaceWaterContentName": any;
        "SurfaceWaterContentTID": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomSnowTemp {
        "Attachments": Attachment[];
        "Layers": SnowTempObs[];
        "shortVersion": any;
        "strings"?: any;
    }
    interface VarsomSnowTempObs {
        "Depth": any;
        "SnowTemp": any;
        "shortVersion": any;
        "strings"?: any;
    }
    interface VarsomStratProfile {
        "Attachments": Attachment[];
        "Layers": StratProfileLayer[];
        "TotalDepth": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomStratProfileLayer {
        "Comment": any;
        "CriticalLayerTID": any;
        "CriticalLayerTName": any;
        "DepthTop": any;
        "GrainFormPrimaryTID": any;
        "GrainFormPrimaryTName": any;
        "GrainFormSecondaryTID": any;
        "GrainFormSecondaryTName": any;
        "GrainSizeAvg": any;
        "GrainSizeAvgMax": any;
        "HardnessBottomTID": any;
        "HardnessBottomTName": any;
        "HardnessTID": any;
        "HardnessTName": any;
        "SortOrder": any;
        "Thickness": any;
        "WetnessTID": any;
        "WetnessTName": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomUrl {
        "UrlDescription": any;
        "UrlLine": any;
        "strings": any;
    }
    interface VarsomWaterLevel {
        "Attachments": Attachment[];
        "IsRiver": any;
        "MeasuredDischarge": any;
        "WaterLevelDescribed": any;
        "WaterLevelRefName": any;
        "WaterLevelRefTID": any;
        "WaterLevelValue": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomWaterLevel2 {
        "Attachments": Attachment[];
        "Comment": any;
        "MarkingReferenceName": any;
        "MarkingReferenceTID": any;
        "MarkingTypeName": any;
        "MarkingTypeTID": any;
        "MeasurementReferenceName": any;
        "MeasurementReferenceTID": any;
        "MeasurementTypeName": any;
        "MeasurementTypeTID": any;
        "MeasuringToolDescription": any;
        "ObservationTimingName": any;
        "ObservationTimingTID": any;
        "WaterAstrayName": any;
        "WaterAstrayTID": any;
        "WaterLevelMeasurement": WaterLevelMeasurement[];
        "WaterLevelMethodName": any;
        "WaterLevelMethodTID": any;
        "WaterLevelStateName": any;
        "WaterLevelStateTID": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomWaterMeasurement {
        "Comment": any;
        "DtMeasurementTime": any;
        "WaterLevelValue": any;
        "shortVersion": any;
        "strings": any;
    }
    interface VarsomWeatherObservation {
        "AirTemperature": any;
        "Attachments"?: Attachment[];
        "CloudCover": any;
        "Comment": any;
        "PrecipitationName": any;
        "PrecipitationTID": any;
        "WindDirection": any;
        "WindDirectionName": any;
        "WindSpeed": any;
        "shortVersion": any;
        "strings": any;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVarsomAttachmentElement extends Components.VarsomAttachment, HTMLStencilElement {
    }
    var HTMLVarsomAttachmentElement: {
        prototype: HTMLVarsomAttachmentElement;
        new (): HTMLVarsomAttachmentElement;
    };
    interface HTMLVarsomAvalancheActivityObsElement extends Components.VarsomAvalancheActivityObs, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheActivityObsElement: {
        prototype: HTMLVarsomAvalancheActivityObsElement;
        new (): HTMLVarsomAvalancheActivityObsElement;
    };
    interface HTMLVarsomAvalancheActivityObs2Element extends Components.VarsomAvalancheActivityObs2, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheActivityObs2Element: {
        prototype: HTMLVarsomAvalancheActivityObs2Element;
        new (): HTMLVarsomAvalancheActivityObs2Element;
    };
    interface HTMLVarsomAvalancheDangerObsElement extends Components.VarsomAvalancheDangerObs, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheDangerObsElement: {
        prototype: HTMLVarsomAvalancheDangerObsElement;
        new (): HTMLVarsomAvalancheDangerObsElement;
    };
    interface HTMLVarsomAvalancheEvalProblemElement extends Components.VarsomAvalancheEvalProblem, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvalProblemElement: {
        prototype: HTMLVarsomAvalancheEvalProblemElement;
        new (): HTMLVarsomAvalancheEvalProblemElement;
    };
    interface HTMLVarsomAvalancheEvalProblem2Element extends Components.VarsomAvalancheEvalProblem2, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvalProblem2Element: {
        prototype: HTMLVarsomAvalancheEvalProblem2Element;
        new (): HTMLVarsomAvalancheEvalProblem2Element;
    };
    interface HTMLVarsomAvalancheEvaluationElement extends Components.VarsomAvalancheEvaluation, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvaluationElement: {
        prototype: HTMLVarsomAvalancheEvaluationElement;
        new (): HTMLVarsomAvalancheEvaluationElement;
    };
    interface HTMLVarsomAvalancheEvaluation2Element extends Components.VarsomAvalancheEvaluation2, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvaluation2Element: {
        prototype: HTMLVarsomAvalancheEvaluation2Element;
        new (): HTMLVarsomAvalancheEvaluation2Element;
    };
    interface HTMLVarsomAvalancheEvaluation3Element extends Components.VarsomAvalancheEvaluation3, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvaluation3Element: {
        prototype: HTMLVarsomAvalancheEvaluation3Element;
        new (): HTMLVarsomAvalancheEvaluation3Element;
    };
    interface HTMLVarsomAvalancheObsElement extends Components.VarsomAvalancheObs, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheObsElement: {
        prototype: HTMLVarsomAvalancheObsElement;
        new (): HTMLVarsomAvalancheObsElement;
    };
    interface HTMLVarsomCompressionTestElement extends Components.VarsomCompressionTest, HTMLStencilElement {
    }
    var HTMLVarsomCompressionTestElement: {
        prototype: HTMLVarsomCompressionTestElement;
        new (): HTMLVarsomCompressionTestElement;
    };
    interface HTMLVarsomDamageObsElement extends Components.VarsomDamageObs, HTMLStencilElement {
    }
    var HTMLVarsomDamageObsElement: {
        prototype: HTMLVarsomDamageObsElement;
        new (): HTMLVarsomDamageObsElement;
    };
    interface HTMLVarsomDangerObsElement extends Components.VarsomDangerObs, HTMLStencilElement {
    }
    var HTMLVarsomDangerObsElement: {
        prototype: HTMLVarsomDangerObsElement;
        new (): HTMLVarsomDangerObsElement;
    };
    interface HTMLVarsomDocElement extends Components.VarsomDoc, HTMLStencilElement {
    }
    var HTMLVarsomDocElement: {
        prototype: HTMLVarsomDocElement;
        new (): HTMLVarsomDocElement;
    };
    interface HTMLVarsomEstimateOfRiskElement extends Components.VarsomEstimateOfRisk, HTMLStencilElement {
    }
    var HTMLVarsomEstimateOfRiskElement: {
        prototype: HTMLVarsomEstimateOfRiskElement;
        new (): HTMLVarsomEstimateOfRiskElement;
    };
    interface HTMLVarsomGeneralObservationElement extends Components.VarsomGeneralObservation, HTMLStencilElement {
    }
    var HTMLVarsomGeneralObservationElement: {
        prototype: HTMLVarsomGeneralObservationElement;
        new (): HTMLVarsomGeneralObservationElement;
    };
    interface HTMLVarsomHeaderElement extends Components.VarsomHeader, HTMLStencilElement {
    }
    var HTMLVarsomHeaderElement: {
        prototype: HTMLVarsomHeaderElement;
        new (): HTMLVarsomHeaderElement;
    };
    interface HTMLVarsomIceCoverObservationElement extends Components.VarsomIceCoverObservation, HTMLStencilElement {
    }
    var HTMLVarsomIceCoverObservationElement: {
        prototype: HTMLVarsomIceCoverObservationElement;
        new (): HTMLVarsomIceCoverObservationElement;
    };
    interface HTMLVarsomIceThicknessElement extends Components.VarsomIceThickness, HTMLStencilElement {
    }
    var HTMLVarsomIceThicknessElement: {
        prototype: HTMLVarsomIceThicknessElement;
        new (): HTMLVarsomIceThicknessElement;
    };
    interface HTMLVarsomIceThicknessLayerElement extends Components.VarsomIceThicknessLayer, HTMLStencilElement {
    }
    var HTMLVarsomIceThicknessLayerElement: {
        prototype: HTMLVarsomIceThicknessLayerElement;
        new (): HTMLVarsomIceThicknessLayerElement;
    };
    interface HTMLVarsomImageSliderElement extends Components.VarsomImageSlider, HTMLStencilElement {
    }
    var HTMLVarsomImageSliderElement: {
        prototype: HTMLVarsomImageSliderElement;
        new (): HTMLVarsomImageSliderElement;
    };
    interface HTMLVarsomIncidentElement extends Components.VarsomIncident, HTMLStencilElement {
    }
    var HTMLVarsomIncidentElement: {
        prototype: HTMLVarsomIncidentElement;
        new (): HTMLVarsomIncidentElement;
    };
    interface HTMLVarsomKeyValueElement extends Components.VarsomKeyValue, HTMLStencilElement {
    }
    var HTMLVarsomKeyValueElement: {
        prototype: HTMLVarsomKeyValueElement;
        new (): HTMLVarsomKeyValueElement;
    };
    interface HTMLVarsomLabelElement extends Components.VarsomLabel, HTMLStencilElement {
    }
    var HTMLVarsomLabelElement: {
        prototype: HTMLVarsomLabelElement;
        new (): HTMLVarsomLabelElement;
    };
    interface HTMLVarsomLabelSmallElement extends Components.VarsomLabelSmall, HTMLStencilElement {
    }
    var HTMLVarsomLabelSmallElement: {
        prototype: HTMLVarsomLabelSmallElement;
        new (): HTMLVarsomLabelSmallElement;
    };
    interface HTMLVarsomLandslideObservationElement extends Components.VarsomLandslideObservation, HTMLStencilElement {
    }
    var HTMLVarsomLandslideObservationElement: {
        prototype: HTMLVarsomLandslideObservationElement;
        new (): HTMLVarsomLandslideObservationElement;
    };
    interface HTMLVarsomLatLngElement extends Components.VarsomLatLng, HTMLStencilElement {
    }
    var HTMLVarsomLatLngElement: {
        prototype: HTMLVarsomLatLngElement;
        new (): HTMLVarsomLatLngElement;
    };
    interface HTMLVarsomMetadataElement extends Components.VarsomMetadata, HTMLStencilElement {
    }
    var HTMLVarsomMetadataElement: {
        prototype: HTMLVarsomMetadataElement;
        new (): HTMLVarsomMetadataElement;
    };
    interface HTMLVarsomObservationElement extends Components.VarsomObservation, HTMLStencilElement {
    }
    var HTMLVarsomObservationElement: {
        prototype: HTMLVarsomObservationElement;
        new (): HTMLVarsomObservationElement;
    };
    interface HTMLVarsomSignsOfDangerElement extends Components.VarsomSignsOfDanger, HTMLStencilElement {
    }
    var HTMLVarsomSignsOfDangerElement: {
        prototype: HTMLVarsomSignsOfDangerElement;
        new (): HTMLVarsomSignsOfDangerElement;
    };
    interface HTMLVarsomSnowCoverObservationElement extends Components.VarsomSnowCoverObservation, HTMLStencilElement {
    }
    var HTMLVarsomSnowCoverObservationElement: {
        prototype: HTMLVarsomSnowCoverObservationElement;
        new (): HTMLVarsomSnowCoverObservationElement;
    };
    interface HTMLVarsomSnowDensityElement extends Components.VarsomSnowDensity, HTMLStencilElement {
    }
    var HTMLVarsomSnowDensityElement: {
        prototype: HTMLVarsomSnowDensityElement;
        new (): HTMLVarsomSnowDensityElement;
    };
    interface HTMLVarsomSnowDensityLayerElement extends Components.VarsomSnowDensityLayer, HTMLStencilElement {
    }
    var HTMLVarsomSnowDensityLayerElement: {
        prototype: HTMLVarsomSnowDensityLayerElement;
        new (): HTMLVarsomSnowDensityLayerElement;
    };
    interface HTMLVarsomSnowProfileElement extends Components.VarsomSnowProfile, HTMLStencilElement {
    }
    var HTMLVarsomSnowProfileElement: {
        prototype: HTMLVarsomSnowProfileElement;
        new (): HTMLVarsomSnowProfileElement;
    };
    interface HTMLVarsomSnowProfile2Element extends Components.VarsomSnowProfile2, HTMLStencilElement {
    }
    var HTMLVarsomSnowProfile2Element: {
        prototype: HTMLVarsomSnowProfile2Element;
        new (): HTMLVarsomSnowProfile2Element;
    };
    interface HTMLVarsomSnowSurfaceObservationElement extends Components.VarsomSnowSurfaceObservation, HTMLStencilElement {
    }
    var HTMLVarsomSnowSurfaceObservationElement: {
        prototype: HTMLVarsomSnowSurfaceObservationElement;
        new (): HTMLVarsomSnowSurfaceObservationElement;
    };
    interface HTMLVarsomSnowTempElement extends Components.VarsomSnowTemp, HTMLStencilElement {
    }
    var HTMLVarsomSnowTempElement: {
        prototype: HTMLVarsomSnowTempElement;
        new (): HTMLVarsomSnowTempElement;
    };
    interface HTMLVarsomSnowTempObsElement extends Components.VarsomSnowTempObs, HTMLStencilElement {
    }
    var HTMLVarsomSnowTempObsElement: {
        prototype: HTMLVarsomSnowTempObsElement;
        new (): HTMLVarsomSnowTempObsElement;
    };
    interface HTMLVarsomStratProfileElement extends Components.VarsomStratProfile, HTMLStencilElement {
    }
    var HTMLVarsomStratProfileElement: {
        prototype: HTMLVarsomStratProfileElement;
        new (): HTMLVarsomStratProfileElement;
    };
    interface HTMLVarsomStratProfileLayerElement extends Components.VarsomStratProfileLayer, HTMLStencilElement {
    }
    var HTMLVarsomStratProfileLayerElement: {
        prototype: HTMLVarsomStratProfileLayerElement;
        new (): HTMLVarsomStratProfileLayerElement;
    };
    interface HTMLVarsomUrlElement extends Components.VarsomUrl, HTMLStencilElement {
    }
    var HTMLVarsomUrlElement: {
        prototype: HTMLVarsomUrlElement;
        new (): HTMLVarsomUrlElement;
    };
    interface HTMLVarsomWaterLevelElement extends Components.VarsomWaterLevel, HTMLStencilElement {
    }
    var HTMLVarsomWaterLevelElement: {
        prototype: HTMLVarsomWaterLevelElement;
        new (): HTMLVarsomWaterLevelElement;
    };
    interface HTMLVarsomWaterLevel2Element extends Components.VarsomWaterLevel2, HTMLStencilElement {
    }
    var HTMLVarsomWaterLevel2Element: {
        prototype: HTMLVarsomWaterLevel2Element;
        new (): HTMLVarsomWaterLevel2Element;
    };
    interface HTMLVarsomWaterMeasurementElement extends Components.VarsomWaterMeasurement, HTMLStencilElement {
    }
    var HTMLVarsomWaterMeasurementElement: {
        prototype: HTMLVarsomWaterMeasurementElement;
        new (): HTMLVarsomWaterMeasurementElement;
    };
    interface HTMLVarsomWeatherObservationElement extends Components.VarsomWeatherObservation, HTMLStencilElement {
    }
    var HTMLVarsomWeatherObservationElement: {
        prototype: HTMLVarsomWeatherObservationElement;
        new (): HTMLVarsomWeatherObservationElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "varsom-attachment": HTMLVarsomAttachmentElement;
        "varsom-avalanche-activity-obs": HTMLVarsomAvalancheActivityObsElement;
        "varsom-avalanche-activity-obs2": HTMLVarsomAvalancheActivityObs2Element;
        "varsom-avalanche-danger-obs": HTMLVarsomAvalancheDangerObsElement;
        "varsom-avalanche-eval-problem": HTMLVarsomAvalancheEvalProblemElement;
        "varsom-avalanche-eval-problem2": HTMLVarsomAvalancheEvalProblem2Element;
        "varsom-avalanche-evaluation": HTMLVarsomAvalancheEvaluationElement;
        "varsom-avalanche-evaluation2": HTMLVarsomAvalancheEvaluation2Element;
        "varsom-avalanche-evaluation3": HTMLVarsomAvalancheEvaluation3Element;
        "varsom-avalanche-obs": HTMLVarsomAvalancheObsElement;
        "varsom-compression-test": HTMLVarsomCompressionTestElement;
        "varsom-damage-obs": HTMLVarsomDamageObsElement;
        "varsom-danger-obs": HTMLVarsomDangerObsElement;
        "varsom-doc": HTMLVarsomDocElement;
        "varsom-estimate-of-risk": HTMLVarsomEstimateOfRiskElement;
        "varsom-general-observation": HTMLVarsomGeneralObservationElement;
        "varsom-header": HTMLVarsomHeaderElement;
        "varsom-ice-cover-observation": HTMLVarsomIceCoverObservationElement;
        "varsom-ice-thickness": HTMLVarsomIceThicknessElement;
        "varsom-ice-thickness-layer": HTMLVarsomIceThicknessLayerElement;
        "varsom-image-slider": HTMLVarsomImageSliderElement;
        "varsom-incident": HTMLVarsomIncidentElement;
        "varsom-key-value": HTMLVarsomKeyValueElement;
        "varsom-label": HTMLVarsomLabelElement;
        "varsom-label-small": HTMLVarsomLabelSmallElement;
        "varsom-landslide-observation": HTMLVarsomLandslideObservationElement;
        "varsom-lat-lng": HTMLVarsomLatLngElement;
        "varsom-metadata": HTMLVarsomMetadataElement;
        "varsom-observation": HTMLVarsomObservationElement;
        "varsom-signs-of-danger": HTMLVarsomSignsOfDangerElement;
        "varsom-snow-cover-observation": HTMLVarsomSnowCoverObservationElement;
        "varsom-snow-density": HTMLVarsomSnowDensityElement;
        "varsom-snow-density-layer": HTMLVarsomSnowDensityLayerElement;
        "varsom-snow-profile": HTMLVarsomSnowProfileElement;
        "varsom-snow-profile2": HTMLVarsomSnowProfile2Element;
        "varsom-snow-surface-observation": HTMLVarsomSnowSurfaceObservationElement;
        "varsom-snow-temp": HTMLVarsomSnowTempElement;
        "varsom-snow-temp-obs": HTMLVarsomSnowTempObsElement;
        "varsom-strat-profile": HTMLVarsomStratProfileElement;
        "varsom-strat-profile-layer": HTMLVarsomStratProfileLayerElement;
        "varsom-url": HTMLVarsomUrlElement;
        "varsom-water-level": HTMLVarsomWaterLevelElement;
        "varsom-water-level2": HTMLVarsomWaterLevel2Element;
        "varsom-water-measurement": HTMLVarsomWaterMeasurementElement;
        "varsom-weather-observation": HTMLVarsomWeatherObservationElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VarsomAttachment {
        "Aspect"?: any;
        "AttachmentId"?: any;
        "AttachmentMimeType"?: any;
        "Comment"?: any;
        "Copyright"?: any;
        "CropImage"?: boolean;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "IsMainAttachment"?: any;
        "Photographer"?: any;
        "RegistrationName"?: any;
        "RegistrationTID"?: any;
        "Url"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomAvalancheActivityObs {
        "Aspect"?: any;
        "Attachments"?: Attachment[];
        "AvalancheActivityObsID"?: any;
        "AvalancheName"?: any;
        "AvalancheTID"?: any;
        "AvalancheTriggerName"?: any;
        "AvalancheTriggerTID"?: any;
        "Comment"?: any;
        "DestructiveSizeName"?: any;
        "DestructiveSizeTID"?: any;
        "DtAvalancheTime"?: any;
        "DtOffAvalancheTime"?: any;
        "EstimatedNumName"?: any;
        "EstimatedNumTID"?: any;
        "HeigthStartZone"?: any;
        "SnowLine"?: any;
        "SnowLineName"?: any;
        "TerrainStartZoneName"?: any;
        "TerrainStartZoneTID"?: any;
        "header"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomAvalancheActivityObs2 {
        "Attachments"?: Attachment[];
        "AvalCauseName"?: any;
        "AvalCauseTID"?: any;
        "AvalPropagationName"?: any;
        "AvalPropagationTID"?: any;
        "AvalTriggerSimpleName"?: any;
        "AvalTriggerSimpleTID"?: any;
        "AvalancheExtName"?: any;
        "AvalancheExtTID"?: any;
        "Comment"?: any;
        "DestructiveSizeName"?: any;
        "DestructiveSizeTID"?: any;
        "DtEnd"?: any;
        "DtStart"?: any;
        "EstimatedNumName"?: any;
        "EstimatedNumTID"?: any;
        "ExposedHeight1"?: any;
        "ExposedHeight2"?: any;
        "ExposedHeightComboName"?: any;
        "ExposedHeightComboTID"?: any;
        "ValidExposition"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomAvalancheDangerObs {
        "Attachments"?: Attachment[];
        "AvalancheDangerObsID"?: any;
        "Comment"?: any;
        "DangerSignName"?: any;
        "DangerSignTID"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomAvalancheEvalProblem {
        "Attachments"?: Attachment[];
        "AvalCauseExtName"?: any;
        "AvalCauseExtTID"?: any;
        "AvalCauseName"?: any;
        "AvalCauseTID"?: any;
        "AvalProbabilityName"?: any;
        "AvalProbabilityTID"?: any;
        "AvalReleaseHeightName"?: any;
        "AvalReleaseHeightTID"?: any;
        "AvalTriggerSimpleName"?: any;
        "AvalTriggerSimpleTID"?: any;
        "AvalancheEvalProblemID"?: any;
        "AvalancheExtName"?: any;
        "AvalancheExtTID"?: any;
        "AvalancheProbabilityAutoText"?: any;
        "AvalancheProblemAutoText"?: any;
        "Comment"?: any;
        "DestructiveSizeExtName"?: any;
        "DestructiveSizeExtTID"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomAvalancheEvalProblem2 {
        "Attachments"?: Attachment[];
        "AvalCauseAttributeCrystalName"?: any;
        "AvalCauseAttributeCrystalTID"?: any;
        "AvalCauseAttributeLightName"?: any;
        "AvalCauseAttributeLightTID"?: any;
        "AvalCauseAttributeSoftName"?: any;
        "AvalCauseAttributeSoftTID"?: any;
        "AvalCauseAttributeThinName"?: any;
        "AvalCauseAttributeThinTID"?: any;
        "AvalCauseDepthName"?: any;
        "AvalCauseDepthTID"?: any;
        "AvalCauseName"?: any;
        "AvalCauseTID"?: any;
        "AvalProbabilityName"?: any;
        "AvalProbabilityTID"?: any;
        "AvalPropagationName"?: any;
        "AvalPropagationTID"?: any;
        "AvalTriggerSimpleName"?: any;
        "AvalTriggerSimpleTID"?: any;
        "AvalancheExtName"?: any;
        "AvalancheExtTID"?: any;
        "Comment"?: any;
        "DestructiveSizeName"?: any;
        "DestructiveSizeTID"?: any;
        "ExposedHeight1"?: any;
        "ExposedHeight2"?: any;
        "ExposedHeightComboName"?: any;
        "ExposedHeightComboTID"?: any;
        "ValidExposition"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomAvalancheEvaluation {
        "Attachments"?: Attachment[];
        "AvalancheDangerName"?: any;
        "AvalancheDangerTID"?: any;
        "AvalancheEvaluation1"?: any;
        "AvalancheProblemName1"?: any;
        "AvalancheProblemName2"?: any;
        "AvalancheProblemName3"?: any;
        "AvalancheProblemTID1"?: any;
        "AvalancheProblemTID2"?: any;
        "AvalancheProblemTID3"?: any;
        "CanPublish"?: any;
        "Comment"?: any;
        "RegID"?: any;
        "ValidExposition"?: any;
        "ValidHeightFrom"?: any;
        "ValidHeightRelative"?: any;
        "ValidHeigtTo"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomAvalancheEvaluation2 {
        "Attachments"?: Attachment[];
        "AvalancheDangerName"?: any;
        "AvalancheDangerTID"?: any;
        "AvalancheDevelopment"?: any;
        "AvalancheEvalProblems"?: any[];
        "AvalancheEvaluation"?: any;
        "Comment"?: any;
        "ExposedClimateName"?: any;
        "ExposedClimateTID"?: any;
        "ExposedHeight1"?: any;
        "ExposedHeight2"?: any;
        "ExposedHeightComboName"?: any;
        "ExposedHeightComboTID"?: any;
        "ValidExposition"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomAvalancheEvaluation3 {
        "Attachments"?: Attachment[];
        "AvalancheDangerName"?: any;
        "AvalancheDangerTID"?: any;
        "AvalancheDevelopment"?: any;
        "AvalancheEvaluation"?: any;
        "ForecastComment"?: any;
        "ForecastCorrectName"?: any;
        "ForecastCorrectTID"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomAvalancheObs {
        "Aspect"?: any;
        "Attachments"?: Attachment[];
        "AvalCauseName"?: any;
        "AvalCauseTID"?: any;
        "AvalancheName"?: any;
        "AvalancheTID"?: any;
        "AvalancheTriggerName"?: any;
        "AvalancheTriggerTID"?: any;
        "Comment"?: any;
        "DestructiveSizeName"?: any;
        "DestructiveSizeTID"?: any;
        "DtAvalancheTime"?: any;
        "FractureHeight"?: any;
        "FractureWidth"?: any;
        "HeightStartZone"?: any;
        "HeightStopZone"?: any;
        "RemotelyTriggered"?: any;
        "SnowLine"?: any;
        "StartLat"?: any;
        "StartLong"?: any;
        "StopLat"?: any;
        "StopLong"?: any;
        "TerrainStartZoneName"?: any;
        "TerrainStartZoneTID"?: any;
        "Trajectory"?: any;
        "ValidExposition"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomCompressionTest {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "ComprTestFractureName"?: any;
        "ComprTestFractureTID"?: any;
        "CompressionTestName"?: any;
        "CompressionTestTID"?: any;
        "FractureDepth"?: any;
        "IncludeInSnowProfile"?: any;
        "PropagationName"?: any;
        "PropagationTID"?: any;
        "PstX"?: any;
        "PstY"?: any;
        "RbRelease"?: any;
        "StabilityEvalName"?: any;
        "StabilityEvalTID"?: any;
        "TapsFracture"?: any;
        "TapsFullPropagation"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomDamageObs {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "DamagePosition"?: any;
        "DamageTypeName"?: string;
        "DamageTypeTID"?: number;
        "GeoHazardName"?: string;
        "GeoHazardTID"?: number;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomDangerObs {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "DangerSignName"?: any;
        "DangerSignTID"?: any;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomDoc {
        "Text"?: any;
    }
    interface VarsomEstimateOfRisk {
        "comment"?: any;
        "dangerSignName"?: any;
        "strings"?: any;
    }
    interface VarsomGeneralObservation {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "ObsComment"?: any;
        "ObsHeader"?: any;
        "Urls"?: Url[];
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomHeader {
        "regId"?: string;
        "region"?: string;
    }
    interface VarsomIceCoverObservation {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "IceCapacityName"?: any;
        "IceCapacityTID"?: any;
        "IceCoverAfterName"?: any;
        "IceCoverAfterTID"?: any;
        "IceCoverBeforeName"?: any;
        "IceCoverBeforeTID"?: any;
        "IceCoverName"?: any;
        "IceCoverTID"?: any;
        "IceSkateabilityName"?: any;
        "IceSkateabilityTID"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomIceThickness {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "DtObsTime"?: any;
        "HardCodedImg"?: any;
        "IceHeightAfter"?: any;
        "IceHeightBefore"?: any;
        "IceThicknessLayers"?: IceThicknessLayer[];
        "IceThicknessSum"?: any;
        "LocationName"?: any;
        "ObsLocationId"?: any;
        "SlushSnow"?: any;
        "SnowDepth"?: any;
        "regId"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomIceThicknessLayer {
        "Comment"?: any;
        "IceLayerName"?: any;
        "IceLayerThickness"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomImageSlider {
        "_images"?: any[];
        "shortVersion"?: string;
        "strings"?: any;
    }
    interface VarsomIncident {
        "ActivityInfluencedName"?: any;
        "ActivityInfluencedTID"?: any;
        "Attachments"?: Attachment[];
        "CasualtiesNum"?: any;
        "Comment"?: any;
        "DamageExtentName"?: any;
        "DamageExtentTID"?: any;
        "DeadNum"?: any;
        "DtEndTime"?: any;
        "EvacuatedNum"?: any;
        "ForecastAccurateName"?: any;
        "ForecastAccurateTID"?: any;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "HarmedNum"?: any;
        "IncidentHeader"?: any;
        "IncidentIngress"?: any;
        "IncidentText"?: any;
        "IncidentURLs"?: any[];
        "InvolvedNum"?: any;
        "LocalKnowledgeName"?: any;
        "LocalKnowledgeTID"?: any;
        "LocalTouristName"?: any;
        "LocalTouristTID"?: any;
        "MaterialDamages"?: any;
        "RescueName"?: any;
        "RescueTID"?: any;
        "SafetyGearName"?: any;
        "SafetyGearTID"?: any;
        "SlopeActivityName"?: any;
        "SlopeActivityTID"?: any;
        "TrafficObstructed"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomKeyValue {
        "_key"?: any;
        "_value"?: any;
        "shortVersion"?: string;
    }
    interface VarsomLabel {
        "label"?: any;
    }
    interface VarsomLabelSmall {
        "label"?: any;
    }
    interface VarsomLandslideObservation {
        "ActivityInfluencedName"?: any;
        "ActivityInfluencedTID"?: any;
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "DamageExtentName"?: any;
        "DamageExtentTID"?: any;
        "DtLandSlideTime"?: any;
        "DtLandSlideTimeEnd"?: any;
        "ForecastAccurateName"?: any;
        "ForecastAccurateTID"?: any;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "LandSlideName"?: any;
        "LandSlideSizeName"?: any;
        "LandSlideSizeTID"?: any;
        "LandSlideTID"?: any;
        "LandSlideTriggerName"?: any;
        "LandSlideTriggerTID"?: any;
        "StartLat"?: any;
        "StartLong"?: any;
        "StopLat"?: any;
        "StopLong"?: any;
        "Urls"?: any[];
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomLatLng {
        "Latitude"?: any;
        "Longitude"?: any;
        "strings"?: any;
    }
    interface VarsomMetadata {
        "competenceLevelName"?: any;
        "dateOfLastUpdate"?: any;
        "dateOfRegistration"?: any;
        "geoHazardName"?: any;
        "moh"?: any;
        "nickname"?: any;
        "observerGroupName"?: any;
        "shortVersion"?: string;
        "strings"?: any;
    }
    interface VarsomObservation {
        "count"?: number;
        "json"?: any;
        "language"?: string;
        "number"?: number;
        "regid"?: string;
        "type"?: string;
        "version"?: string;
    }
    interface VarsomSignsOfDanger {
        "Comment"?: any;
        "Type"?: any;
        "strings"?: any;
    }
    interface VarsomSnowCoverObservation {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "CriticalLayerExists"?: any;
        "CriticalLayerLocation"?: any;
        "CriticalLayerName"?: any;
        "CriticalLayerTID"?: any;
        "DepthHoarThickness"?: any;
        "SnowPilotRef"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomSnowDensity {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "CylinderDiameter"?: any;
        "Layers"?: SnowDensityLayer[];
        "TareWeight"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomSnowDensityLayer {
        "Depth"?: any;
        "SortOrder"?: any;
        "Thickness"?: any;
        "WaterEquivalent"?: any;
        "Weight"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomSnowProfile {
        "Aspect"?: any;
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "Copyright"?: any;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "Photographer"?: any;
        "RegistrationName"?: any;
        "RegistrationTID"?: any;
        "Url"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomSnowProfile2 {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "Exposition"?: any;
        "ImageUrl"?: any;
        "IsProfileToGround"?: any;
        "RegId"?: any;
        "SlopeAngle"?: any;
        "SnowDensity"?: SnowDensity[];
        "SnowTemp"?: any;
        "StratProfile"?: any;
        "TotalDepth"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomSnowSurfaceObservation {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "FootPenetration"?: any;
        "HeightLimitLayeredSnow"?: any;
        "NewSnowDepth24"?: any;
        "NewSnowLine"?: any;
        "SkiConditionsName"?: any;
        "SkiConditionsTID"?: any;
        "SnowDepth"?: any;
        "SnowDriftName"?: any;
        "SnowDriftTID"?: any;
        "SnowLine"?: any;
        "SnowSurfaceName"?: any;
        "SnowSurfaceTID"?: any;
        "SurfaceRoughnessName"?: any;
        "SurfaceWaterContentName"?: any;
        "SurfaceWaterContentTID"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomSnowTemp {
        "Attachments"?: Attachment[];
        "Layers"?: SnowTempObs[];
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomSnowTempObs {
        "Depth"?: any;
        "SnowTemp"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomStratProfile {
        "Attachments"?: Attachment[];
        "Layers"?: StratProfileLayer[];
        "TotalDepth"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomStratProfileLayer {
        "Comment"?: any;
        "CriticalLayerTID"?: any;
        "CriticalLayerTName"?: any;
        "DepthTop"?: any;
        "GrainFormPrimaryTID"?: any;
        "GrainFormPrimaryTName"?: any;
        "GrainFormSecondaryTID"?: any;
        "GrainFormSecondaryTName"?: any;
        "GrainSizeAvg"?: any;
        "GrainSizeAvgMax"?: any;
        "HardnessBottomTID"?: any;
        "HardnessBottomTName"?: any;
        "HardnessTID"?: any;
        "HardnessTName"?: any;
        "SortOrder"?: any;
        "Thickness"?: any;
        "WetnessTID"?: any;
        "WetnessTName"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomUrl {
        "UrlDescription"?: any;
        "UrlLine"?: any;
        "strings"?: any;
    }
    interface VarsomWaterLevel {
        "Attachments"?: Attachment[];
        "IsRiver"?: any;
        "MeasuredDischarge"?: any;
        "WaterLevelDescribed"?: any;
        "WaterLevelRefName"?: any;
        "WaterLevelRefTID"?: any;
        "WaterLevelValue"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomWaterLevel2 {
        "Attachments"?: Attachment[];
        "Comment"?: any;
        "MarkingReferenceName"?: any;
        "MarkingReferenceTID"?: any;
        "MarkingTypeName"?: any;
        "MarkingTypeTID"?: any;
        "MeasurementReferenceName"?: any;
        "MeasurementReferenceTID"?: any;
        "MeasurementTypeName"?: any;
        "MeasurementTypeTID"?: any;
        "MeasuringToolDescription"?: any;
        "ObservationTimingName"?: any;
        "ObservationTimingTID"?: any;
        "WaterAstrayName"?: any;
        "WaterAstrayTID"?: any;
        "WaterLevelMeasurement"?: WaterLevelMeasurement[];
        "WaterLevelMethodName"?: any;
        "WaterLevelMethodTID"?: any;
        "WaterLevelStateName"?: any;
        "WaterLevelStateTID"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomWaterMeasurement {
        "Comment"?: any;
        "DtMeasurementTime"?: any;
        "WaterLevelValue"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface VarsomWeatherObservation {
        "AirTemperature"?: any;
        "Attachments"?: Attachment[];
        "CloudCover"?: any;
        "Comment"?: any;
        "PrecipitationName"?: any;
        "PrecipitationTID"?: any;
        "WindDirection"?: any;
        "WindDirectionName"?: any;
        "WindSpeed"?: any;
        "shortVersion"?: any;
        "strings"?: any;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "varsom-attachment": VarsomAttachment;
        "varsom-avalanche-activity-obs": VarsomAvalancheActivityObs;
        "varsom-avalanche-activity-obs2": VarsomAvalancheActivityObs2;
        "varsom-avalanche-danger-obs": VarsomAvalancheDangerObs;
        "varsom-avalanche-eval-problem": VarsomAvalancheEvalProblem;
        "varsom-avalanche-eval-problem2": VarsomAvalancheEvalProblem2;
        "varsom-avalanche-evaluation": VarsomAvalancheEvaluation;
        "varsom-avalanche-evaluation2": VarsomAvalancheEvaluation2;
        "varsom-avalanche-evaluation3": VarsomAvalancheEvaluation3;
        "varsom-avalanche-obs": VarsomAvalancheObs;
        "varsom-compression-test": VarsomCompressionTest;
        "varsom-damage-obs": VarsomDamageObs;
        "varsom-danger-obs": VarsomDangerObs;
        "varsom-doc": VarsomDoc;
        "varsom-estimate-of-risk": VarsomEstimateOfRisk;
        "varsom-general-observation": VarsomGeneralObservation;
        "varsom-header": VarsomHeader;
        "varsom-ice-cover-observation": VarsomIceCoverObservation;
        "varsom-ice-thickness": VarsomIceThickness;
        "varsom-ice-thickness-layer": VarsomIceThicknessLayer;
        "varsom-image-slider": VarsomImageSlider;
        "varsom-incident": VarsomIncident;
        "varsom-key-value": VarsomKeyValue;
        "varsom-label": VarsomLabel;
        "varsom-label-small": VarsomLabelSmall;
        "varsom-landslide-observation": VarsomLandslideObservation;
        "varsom-lat-lng": VarsomLatLng;
        "varsom-metadata": VarsomMetadata;
        "varsom-observation": VarsomObservation;
        "varsom-signs-of-danger": VarsomSignsOfDanger;
        "varsom-snow-cover-observation": VarsomSnowCoverObservation;
        "varsom-snow-density": VarsomSnowDensity;
        "varsom-snow-density-layer": VarsomSnowDensityLayer;
        "varsom-snow-profile": VarsomSnowProfile;
        "varsom-snow-profile2": VarsomSnowProfile2;
        "varsom-snow-surface-observation": VarsomSnowSurfaceObservation;
        "varsom-snow-temp": VarsomSnowTemp;
        "varsom-snow-temp-obs": VarsomSnowTempObs;
        "varsom-strat-profile": VarsomStratProfile;
        "varsom-strat-profile-layer": VarsomStratProfileLayer;
        "varsom-url": VarsomUrl;
        "varsom-water-level": VarsomWaterLevel;
        "varsom-water-level2": VarsomWaterLevel2;
        "varsom-water-measurement": VarsomWaterMeasurement;
        "varsom-weather-observation": VarsomWeatherObservation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "varsom-attachment": LocalJSX.VarsomAttachment & JSXBase.HTMLAttributes<HTMLVarsomAttachmentElement>;
            "varsom-avalanche-activity-obs": LocalJSX.VarsomAvalancheActivityObs & JSXBase.HTMLAttributes<HTMLVarsomAvalancheActivityObsElement>;
            "varsom-avalanche-activity-obs2": LocalJSX.VarsomAvalancheActivityObs2 & JSXBase.HTMLAttributes<HTMLVarsomAvalancheActivityObs2Element>;
            "varsom-avalanche-danger-obs": LocalJSX.VarsomAvalancheDangerObs & JSXBase.HTMLAttributes<HTMLVarsomAvalancheDangerObsElement>;
            "varsom-avalanche-eval-problem": LocalJSX.VarsomAvalancheEvalProblem & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvalProblemElement>;
            "varsom-avalanche-eval-problem2": LocalJSX.VarsomAvalancheEvalProblem2 & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvalProblem2Element>;
            "varsom-avalanche-evaluation": LocalJSX.VarsomAvalancheEvaluation & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvaluationElement>;
            "varsom-avalanche-evaluation2": LocalJSX.VarsomAvalancheEvaluation2 & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvaluation2Element>;
            "varsom-avalanche-evaluation3": LocalJSX.VarsomAvalancheEvaluation3 & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvaluation3Element>;
            "varsom-avalanche-obs": LocalJSX.VarsomAvalancheObs & JSXBase.HTMLAttributes<HTMLVarsomAvalancheObsElement>;
            "varsom-compression-test": LocalJSX.VarsomCompressionTest & JSXBase.HTMLAttributes<HTMLVarsomCompressionTestElement>;
            "varsom-damage-obs": LocalJSX.VarsomDamageObs & JSXBase.HTMLAttributes<HTMLVarsomDamageObsElement>;
            "varsom-danger-obs": LocalJSX.VarsomDangerObs & JSXBase.HTMLAttributes<HTMLVarsomDangerObsElement>;
            "varsom-doc": LocalJSX.VarsomDoc & JSXBase.HTMLAttributes<HTMLVarsomDocElement>;
            "varsom-estimate-of-risk": LocalJSX.VarsomEstimateOfRisk & JSXBase.HTMLAttributes<HTMLVarsomEstimateOfRiskElement>;
            "varsom-general-observation": LocalJSX.VarsomGeneralObservation & JSXBase.HTMLAttributes<HTMLVarsomGeneralObservationElement>;
            "varsom-header": LocalJSX.VarsomHeader & JSXBase.HTMLAttributes<HTMLVarsomHeaderElement>;
            "varsom-ice-cover-observation": LocalJSX.VarsomIceCoverObservation & JSXBase.HTMLAttributes<HTMLVarsomIceCoverObservationElement>;
            "varsom-ice-thickness": LocalJSX.VarsomIceThickness & JSXBase.HTMLAttributes<HTMLVarsomIceThicknessElement>;
            "varsom-ice-thickness-layer": LocalJSX.VarsomIceThicknessLayer & JSXBase.HTMLAttributes<HTMLVarsomIceThicknessLayerElement>;
            "varsom-image-slider": LocalJSX.VarsomImageSlider & JSXBase.HTMLAttributes<HTMLVarsomImageSliderElement>;
            "varsom-incident": LocalJSX.VarsomIncident & JSXBase.HTMLAttributes<HTMLVarsomIncidentElement>;
            "varsom-key-value": LocalJSX.VarsomKeyValue & JSXBase.HTMLAttributes<HTMLVarsomKeyValueElement>;
            "varsom-label": LocalJSX.VarsomLabel & JSXBase.HTMLAttributes<HTMLVarsomLabelElement>;
            "varsom-label-small": LocalJSX.VarsomLabelSmall & JSXBase.HTMLAttributes<HTMLVarsomLabelSmallElement>;
            "varsom-landslide-observation": LocalJSX.VarsomLandslideObservation & JSXBase.HTMLAttributes<HTMLVarsomLandslideObservationElement>;
            "varsom-lat-lng": LocalJSX.VarsomLatLng & JSXBase.HTMLAttributes<HTMLVarsomLatLngElement>;
            "varsom-metadata": LocalJSX.VarsomMetadata & JSXBase.HTMLAttributes<HTMLVarsomMetadataElement>;
            "varsom-observation": LocalJSX.VarsomObservation & JSXBase.HTMLAttributes<HTMLVarsomObservationElement>;
            "varsom-signs-of-danger": LocalJSX.VarsomSignsOfDanger & JSXBase.HTMLAttributes<HTMLVarsomSignsOfDangerElement>;
            "varsom-snow-cover-observation": LocalJSX.VarsomSnowCoverObservation & JSXBase.HTMLAttributes<HTMLVarsomSnowCoverObservationElement>;
            "varsom-snow-density": LocalJSX.VarsomSnowDensity & JSXBase.HTMLAttributes<HTMLVarsomSnowDensityElement>;
            "varsom-snow-density-layer": LocalJSX.VarsomSnowDensityLayer & JSXBase.HTMLAttributes<HTMLVarsomSnowDensityLayerElement>;
            "varsom-snow-profile": LocalJSX.VarsomSnowProfile & JSXBase.HTMLAttributes<HTMLVarsomSnowProfileElement>;
            "varsom-snow-profile2": LocalJSX.VarsomSnowProfile2 & JSXBase.HTMLAttributes<HTMLVarsomSnowProfile2Element>;
            "varsom-snow-surface-observation": LocalJSX.VarsomSnowSurfaceObservation & JSXBase.HTMLAttributes<HTMLVarsomSnowSurfaceObservationElement>;
            "varsom-snow-temp": LocalJSX.VarsomSnowTemp & JSXBase.HTMLAttributes<HTMLVarsomSnowTempElement>;
            "varsom-snow-temp-obs": LocalJSX.VarsomSnowTempObs & JSXBase.HTMLAttributes<HTMLVarsomSnowTempObsElement>;
            "varsom-strat-profile": LocalJSX.VarsomStratProfile & JSXBase.HTMLAttributes<HTMLVarsomStratProfileElement>;
            "varsom-strat-profile-layer": LocalJSX.VarsomStratProfileLayer & JSXBase.HTMLAttributes<HTMLVarsomStratProfileLayerElement>;
            "varsom-url": LocalJSX.VarsomUrl & JSXBase.HTMLAttributes<HTMLVarsomUrlElement>;
            "varsom-water-level": LocalJSX.VarsomWaterLevel & JSXBase.HTMLAttributes<HTMLVarsomWaterLevelElement>;
            "varsom-water-level2": LocalJSX.VarsomWaterLevel2 & JSXBase.HTMLAttributes<HTMLVarsomWaterLevel2Element>;
            "varsom-water-measurement": LocalJSX.VarsomWaterMeasurement & JSXBase.HTMLAttributes<HTMLVarsomWaterMeasurementElement>;
            "varsom-weather-observation": LocalJSX.VarsomWeatherObservation & JSXBase.HTMLAttributes<HTMLVarsomWeatherObservationElement>;
        }
    }
}
