/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Attachment, AvalancheEvalProblem, IceThicknessLayer, LatLng, Observation, SnowDensity, SnowDensityLayer, SnowTemp, SnowTempObs, StratProfile, StratProfileLayer, Url, WaterLevelMeasurement } from "./models/observation-model";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface VarsomAttachment {
        "Aspect"?: any;
        "AttachmentId"?: any;
        "AttachmentMimeType"?: any;
        "Comment": any;
        "Copyright": any;
        "CropImage"?: boolean;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "IsMainAttachment"?: any;
        "Photographer": any;
        "RegistrationName": any;
        "RegistrationTID"?: any;
        "Url": any;
    }
    interface VarsomAvalancheActivityObs {
        "Aspect": number;
        "Attachments": Attachment[];
        "AvalancheActivityObsID": number;
        "AvalancheName": string;
        "AvalancheTID": number;
        "AvalancheTriggerName": string;
        "AvalancheTriggerTID": number;
        "Comment": string;
        "DestructiveSizeName": string;
        "DestructiveSizeTID": number;
        "DtAvalancheTime": string;
        "DtOffAvalancheTime": string;
        "EstimatedNumName": string;
        "EstimatedNumTID": number;
        "HeigthStartZone": number;
        "SnowLine": number;
        "SnowLineName": string;
        "TerrainStartZoneName": string;
        "TerrainStartZoneTID": number;
        "header": string;
        "shortVersion": string;
    }
    interface VarsomAvalancheActivityObs2 {
        "Attachments": Attachment[];
        "AvalCauseName": string;
        "AvalCauseTID": number;
        "AvalPropagationName": string;
        "AvalPropagationTID": number;
        "AvalTriggerSimpleName": string;
        "AvalTriggerSimpleTID": number;
        "AvalancheExtName": string;
        "AvalancheExtTID": number;
        "Comment": string;
        "DestructiveSizeName": string;
        "DestructiveSizeTID": number;
        "DtEnd": string;
        "DtStart": string;
        "EstimatedNumName": string;
        "EstimatedNumTID": number;
        "ExposedHeight1": number;
        "ExposedHeight2": number;
        "ExposedHeightComboName": string;
        "ExposedHeightComboTID": number;
        "ValidExposition": string;
        "shortVersion": string;
    }
    interface VarsomAvalancheDangerObs {
        "Attachments": Attachment[];
        "AvalancheDangerObsID": number;
        "Comment": string;
        "DangerSignName": string;
        "DangerSignTID": number;
        "shortVersion": string;
    }
    interface VarsomAvalancheEvalProblem {
        "Attachments": Attachment[];
        "AvalCauseExtName": string;
        "AvalCauseExtTID": number;
        "AvalCauseName": string;
        "AvalCauseTID": number;
        "AvalProbabilityName": string;
        "AvalProbabilityTID": number;
        "AvalReleaseHeightName": string;
        "AvalReleaseHeightTID": number;
        "AvalTriggerSimpleName": string;
        "AvalTriggerSimpleTID": number;
        "AvalancheEvalProblemID": number;
        "AvalancheExtName": string;
        "AvalancheExtTID": number;
        "AvalancheProbabilityAutoText": string;
        "AvalancheProblemAutoText": string;
        "Comment": string;
        "DestructiveSizeExtName": string;
        "DestructiveSizeExtTID": number;
        "shortVersion": string;
    }
    interface VarsomAvalancheEvalProblem2 {
        "Attachments": Attachment[];
        "AvalCauseAttributeCrystalName": string;
        "AvalCauseAttributeCrystalTID": number;
        "AvalCauseAttributeLightName": string;
        "AvalCauseAttributeLightTID": number;
        "AvalCauseAttributeSoftName": string;
        "AvalCauseAttributeSoftTID": number;
        "AvalCauseAttributeThinName": string;
        "AvalCauseAttributeThinTID": number;
        "AvalCauseDepthName": string;
        "AvalCauseDepthTID": number;
        "AvalCauseName": string;
        "AvalCauseTID": number;
        "AvalProbabilityName": string;
        "AvalProbabilityTID": number;
        "AvalPropagationName": string;
        "AvalPropagationTID": number;
        "AvalTriggerSimpleName": string;
        "AvalTriggerSimpleTID": number;
        "AvalancheExtName": string;
        "AvalancheExtTID": number;
        "Comment": string;
        "DestructiveSizeName": string;
        "DestructiveSizeTID": number;
        "ExposedHeight1": number;
        "ExposedHeight2": number;
        "ExposedHeightComboName": string;
        "ExposedHeightComboTID": number;
        "ValidExposition": string;
        "shortVersion": string;
    }
    interface VarsomAvalancheEvaluation {
        "Attachments": Attachment[];
        "AvalancheDangerName": string;
        "AvalancheDangerTID": number;
        "AvalancheEvaluation1": string;
        "AvalancheProblemName1": string;
        "AvalancheProblemName2": string;
        "AvalancheProblemName3": string;
        "AvalancheProblemTID1": number;
        "AvalancheProblemTID2": number;
        "AvalancheProblemTID3": number;
        "CanPublish": boolean;
        "Comment": string;
        "ValidExposition": string;
        "ValidHeightFrom": number;
        "ValidHeightRelative": string;
        "ValidHeigtTo": number;
        "shortVersion": string;
    }
    interface VarsomAvalancheEvaluation2 {
        "Attachments": Attachment[];
        "AvalancheDangerName": string;
        "AvalancheDangerTID": number;
        "AvalancheDevelopment": string;
        "AvalancheEvalProblems": AvalancheEvalProblem[];
        "AvalancheEvaluation": string;
        "Comment": string;
        "ExposedClimateName": string;
        "ExposedClimateTID": number;
        "ExposedHeight1": number;
        "ExposedHeight2": number;
        "ExposedHeightComboName": string;
        "ExposedHeightComboTID": number;
        "ValidExposition": string;
        "shortVersion": string;
    }
    interface VarsomAvalancheEvaluation3 {
        "Attachments": Attachment[];
        "AvalancheDangerName": string;
        "AvalancheDangerTID": number;
        "AvalancheDevelopment": string;
        "AvalancheEvaluation": string;
        "ForecastComment": string;
        "ForecastCorrectName": string;
        "ForecastCorrectTID": number;
        "shortVersion": string;
    }
    interface VarsomAvalancheObs {
        "Aspect": number;
        "Attachments": Attachment[];
        "AvalCauseName": string;
        "AvalCauseTID": number;
        "AvalancheName": string;
        "AvalancheTID": number;
        "AvalancheTriggerName": string;
        "AvalancheTriggerTID": number;
        "Comment": string;
        "DestructiveSizeName": string;
        "DestructiveSizeTID": number;
        "DtAvalancheTime": string;
        "FractureHeight": number;
        "FractureWidth": number;
        "HeightStartZone": number;
        "HeightStopZone": number;
        "Observation": Observation;
        "RemotelyTriggered": boolean;
        "SnowLine": number;
        "StartLat": number;
        "StartLong": number;
        "StopLat": number;
        "StopLong": number;
        "TerrainStartZoneName": string;
        "TerrainStartZoneTID": number;
        "Trajectory": string;
        "ValidExposition": string;
        "shortVersion": string;
    }
    interface VarsomCompressionTest {
        "Attachments": Attachment[];
        "Comment": string;
        "ComprTestFractureName": string;
        "ComprTestFractureTID": number;
        "CompressionTestName": string;
        "CompressionTestTID": number;
        "FractureDepth": number;
        "IncludeInSnowProfile": boolean;
        "PropagationName": string;
        "PropagationTID": number;
        "PstX": number;
        "PstY": number;
        "RbRelease": number;
        "StabilityEvalName": string;
        "StabilityEvalTID": number;
        "TapsFracture": number;
        "TapsFullPropagation": number;
        "shortVersion": string;
    }
    interface VarsomDamageObs {
        "Attachments"?: Attachment[];
        "Comment": string;
        "DamagePosition": LatLng;
        "DamageTypeName": string;
        "DamageTypeTID": number;
        "GeoHazardName": string;
        "GeoHazardTID": number;
        "shortVersion": string;
    }
    interface VarsomDangerObs {
        "Attachments": Attachment[];
        "Comment": string;
        "DangerSignName": string;
        "DangerSignTID": number;
        "GeoHazardName": string;
        "GeoHazardTID": number;
        "shortVersion": string;
    }
    interface VarsomDoc {
        "Text": any;
    }
    interface VarsomExposedHeight {
        "ExposedHeight1": any;
        "ExposedHeight2": any;
        "ValidExposition": any;
    }
    interface VarsomGeneralObservation {
        "Attachments": Attachment[];
        "Comment": string;
        "GeoHazardName": string;
        "GeoHazardTID": number;
        "ObsComment": string;
        "ObsHeader": string;
        "Urls": Url[];
        "shortVersion": string;
    }
    interface VarsomHeader {
        "regId": string;
        "region": string;
    }
    interface VarsomIceCoverObservation {
        "Attachments": Attachment[];
        "Comment": string;
        "IceCapacityName": string;
        "IceCapacityTID": number;
        "IceCoverAfterName": string;
        "IceCoverAfterTID": number;
        "IceCoverBeforeName": string;
        "IceCoverBeforeTID": number;
        "IceCoverName": string;
        "IceCoverTID": number;
        "IceSkateabilityName": string;
        "IceSkateabilityTID": number;
        "shortVersion": string;
    }
    interface VarsomIceThickness {
        "Attachments": Attachment[];
        "Comment": string;
        "DtObsTime": string;
        "HardCodedImg": string;
        "IceHeightAfter": number;
        "IceHeightBefore": number;
        "IceThicknessLayers": IceThicknessLayer[];
        "IceThicknessSum": number;
        "LocationName": string;
        "ObsLocationId": number;
        "SlushSnow": number;
        "SnowDepth": number;
        "regId": number;
        "shortVersion": string;
    }
    interface VarsomIceThicknessLayer {
        "Comment": string;
        "IceLayerName": string;
        "IceLayerThickness": number;
        "shortVersion": string;
    }
    interface VarsomImageSlider {
        "_images": any[];
        "observation": Observation;
        "shortVersion": string;
    }
    interface VarsomImageSliderMobile {
        "_images": any[];
        "observation": Observation;
        "shortVersion": string;
    }
    interface VarsomIncident {
        "ActivityInfluencedName": string;
        "ActivityInfluencedTID": number;
        "Attachments": Attachment[];
        "CasualtiesNum": number;
        "Comment": string;
        "DamageExtentName": string;
        "DamageExtentTID": number;
        "DeadNum": number;
        "DtEndTime": string;
        "EvacuatedNum": number;
        "ForecastAccurateName": string;
        "ForecastAccurateTID": number;
        "GeoHazardName": string;
        "GeoHazardTID": number;
        "HarmedNum": number;
        "IncidentHeader": string;
        "IncidentIngress": string;
        "IncidentText": string;
        "IncidentURLs": Url[];
        "InvolvedNum": number;
        "LocalKnowledgeName": string;
        "LocalKnowledgeTID": number;
        "LocalTouristName": string;
        "LocalTouristTID": number;
        "MaterialDamages": boolean;
        "RescueName": string;
        "RescueTID": number;
        "SafetyGearName": string;
        "SafetyGearTID": number;
        "SlopeActivityName": string;
        "SlopeActivityTID": number;
        "TrafficObstructed": boolean;
        "shortVersion": string;
    }
    interface VarsomKeyValue {
        "_key": string;
        "_value"?: string | number | boolean;
        "shortVersion": string;
    }
    interface VarsomLabel {
        "label": string;
    }
    interface VarsomLabelSmall {
        "label": string;
    }
    interface VarsomLandslideObservation {
        "ActivityInfluencedName"?: string;
        "ActivityInfluencedTID"?: number;
        "Attachments": Attachment[];
        "Comment"?: string;
        "DamageExtentName"?: string;
        "DamageExtentTID"?: number;
        "DtLandSlideTime"?: string;
        "DtLandSlideTimeEnd"?: string;
        "ForecastAccurateName"?: string;
        "ForecastAccurateTID"?: number;
        "GeoHazardName"?: string;
        "GeoHazardTID"?: number;
        "LandSlideName"?: string;
        "LandSlideSizeName"?: string;
        "LandSlideSizeTID"?: number;
        "LandSlideTID"?: number;
        "LandSlideTriggerName"?: string;
        "LandSlideTriggerTID"?: number;
        "StartLat"?: number;
        "StartLong"?: number;
        "StopLat"?: number;
        "StopLong"?: number;
        "Urls"?: Url[];
        "shortVersion": string;
    }
    interface VarsomMetadata {
        "competenceLevelName": string;
        "dateOfLastUpdate"?: string;
        "dateOfObservation": string;
        "dateOfRegistration": string;
        "geoHazardName": string;
        "moh": number;
        "nickname": string;
        "observerGroupName": string;
        "shortVersion": string;
    }
    interface VarsomObservation {
        "count": number;
        "json": any;
        "number": number;
        "regid": string;
        "type": string;
        "version": string;
    }
    interface VarsomRegobsLink {
        "regId": number;
    }
    interface VarsomSnowCoverObservation {
        "Attachments": Attachment[];
        "Comment": string;
        "CriticalLayerExists": boolean;
        "CriticalLayerLocation": number;
        "CriticalLayerName": string;
        "CriticalLayerTID": number;
        "DepthHoarThickness": number;
        "SnowPilotRef": string;
        "shortVersion": string;
    }
    interface VarsomSnowDensity {
        "Attachments": Attachment[];
        "Comment": string;
        "CylinderDiameter": number;
        "Density": number;
        "Depth": number;
        "Layers": SnowDensityLayer[];
        "TareWeight": number;
        "Weight": number;
        "shortVersion": string;
    }
    interface VarsomSnowDensityLayer {
        "Density": number;
        "Depth": number;
        "SortOrder": number;
        "Thickness": number;
        "WaterEquivalent": number;
        "Weight": number;
        "shortVersion": string;
    }
    interface VarsomSnowProfile {
        "Aspect": number;
        "Attachments": Attachment[];
        "Comment": string;
        "Copyright": string;
        "GeoHazardName": string;
        "GeoHazardTID": number;
        "Photographer": string;
        "RegistrationName": string;
        "RegistrationTID": number;
        "Url": string;
        "shortVersion": string;
    }
    interface VarsomSnowProfile2 {
        "Attachments": Attachment[];
        "Comment": string;
        "Exposition": number;
        "ImageUrl": string;
        "IsProfileToGround": boolean;
        "RegId": number;
        "SlopeAngle": number;
        "SnowDensity": SnowDensity[];
        "SnowTemp": SnowTemp;
        "StratProfile": StratProfile;
        "TotalDepth": number;
        "Weight": number;
        "shortVersion": string;
    }
    interface VarsomSnowSurfaceObservation {
        "Attachments": Attachment[];
        "Comment": string;
        "FootPenetration": number;
        "HeightLimitLayeredSnow": number;
        "NewSnowDepth24": number;
        "NewSnowLine": number;
        "SkiConditionsName": string;
        "SkiConditionsTID": number;
        "SnowDepth": number;
        "SnowDriftName": string;
        "SnowDriftTID": number;
        "SnowLine": number;
        "SnowSurfaceName": string;
        "SnowSurfaceTID": number;
        "SurfaceRoughnessName": string;
        "SurfaceWaterContentName": string;
        "SurfaceWaterContentTID": number;
        "shortVersion": string;
    }
    interface VarsomSnowTemp {
        "Attachments": Attachment[];
        "Layers": SnowTempObs[];
        "shortVersion": string;
    }
    interface VarsomSnowTempObs {
        "Depth": number;
        "SnowTemp": number;
        "shortVersion": string;
    }
    interface VarsomStaticMap {
        "allowZoom"?: boolean;
        "avalanche"?: boolean;
        "observation"?: Observation;
        "small"?: boolean;
    }
    interface VarsomStratProfile {
        "Attachments": Attachment[];
        "Layers": StratProfileLayer[];
        "TotalDepth": number;
        "shortVersion": string;
    }
    interface VarsomStratProfileLayer {
        "Comment": string;
        "CriticalLayerTID": number;
        "CriticalLayerTName": string;
        "DepthTop": number;
        "GrainFormPrimaryTID": number;
        "GrainFormPrimaryTName": string;
        "GrainFormSecondaryTID": number;
        "GrainFormSecondaryTName": string;
        "GrainSizeAvg": number;
        "GrainSizeAvgMax": number;
        "HardnessBottomTID": number;
        "HardnessBottomTName": string;
        "HardnessTID": number;
        "HardnessTName": string;
        "SortOrder": number;
        "Thickness": number;
        "WetnessTID": number;
        "WetnessTName": string;
        "shortVersion": string;
    }
    interface VarsomUrl {
        "UrlDescription": string;
        "UrlLine": string;
    }
    interface VarsomWaterLevel {
        "Attachments": Attachment[];
        "IsRiver": boolean;
        "MeasuredDischarge": number;
        "WaterLevelDescribed": number;
        "WaterLevelRefName": number;
        "WaterLevelRefTID": number;
        "WaterLevelValue": number;
        "shortVersion": string;
    }
    interface VarsomWaterLevel2 {
        "Attachments": Attachment[];
        "Comment": string;
        "MarkingReferenceName": string;
        "MarkingReferenceTID": number;
        "MarkingTypeName": string;
        "MarkingTypeTID": number;
        "MeasurementReferenceName": string;
        "MeasurementReferenceTID": number;
        "MeasurementTypeName": string;
        "MeasurementTypeTID": number;
        "MeasuringToolDescription": string;
        "ObservationTimingName": string;
        "ObservationTimingTID": number;
        "WaterAstrayName": string;
        "WaterAstrayTID": number;
        "WaterLevelMeasurement": WaterLevelMeasurement[];
        "WaterLevelMethodName": string;
        "WaterLevelMethodTID": number;
        "WaterLevelStateName": string;
        "WaterLevelStateTID": number;
        "shortVersion": string;
    }
    interface VarsomWaterMeasurement {
        "Comment": string;
        "DtMeasurementTime": string;
        "WaterLevelValue": number;
        "shortVersion": string;
    }
    interface VarsomWeatherObservation {
        "AirTemperature": number;
        "Attachments"?: Attachment[];
        "CloudCover": number;
        "Comment": string;
        "PrecipitationName": string;
        "PrecipitationTID": number;
        "WindDirection": number;
        "WindDirectionName": string;
        "WindSpeed": number;
        "shortVersion": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVarsomAttachmentElement extends Components.VarsomAttachment, HTMLStencilElement {
    }
    var HTMLVarsomAttachmentElement: {
        prototype: HTMLVarsomAttachmentElement;
        new (): HTMLVarsomAttachmentElement;
    };
    interface HTMLVarsomAvalancheActivityObsElement extends Components.VarsomAvalancheActivityObs, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheActivityObsElement: {
        prototype: HTMLVarsomAvalancheActivityObsElement;
        new (): HTMLVarsomAvalancheActivityObsElement;
    };
    interface HTMLVarsomAvalancheActivityObs2Element extends Components.VarsomAvalancheActivityObs2, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheActivityObs2Element: {
        prototype: HTMLVarsomAvalancheActivityObs2Element;
        new (): HTMLVarsomAvalancheActivityObs2Element;
    };
    interface HTMLVarsomAvalancheDangerObsElement extends Components.VarsomAvalancheDangerObs, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheDangerObsElement: {
        prototype: HTMLVarsomAvalancheDangerObsElement;
        new (): HTMLVarsomAvalancheDangerObsElement;
    };
    interface HTMLVarsomAvalancheEvalProblemElement extends Components.VarsomAvalancheEvalProblem, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvalProblemElement: {
        prototype: HTMLVarsomAvalancheEvalProblemElement;
        new (): HTMLVarsomAvalancheEvalProblemElement;
    };
    interface HTMLVarsomAvalancheEvalProblem2Element extends Components.VarsomAvalancheEvalProblem2, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvalProblem2Element: {
        prototype: HTMLVarsomAvalancheEvalProblem2Element;
        new (): HTMLVarsomAvalancheEvalProblem2Element;
    };
    interface HTMLVarsomAvalancheEvaluationElement extends Components.VarsomAvalancheEvaluation, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvaluationElement: {
        prototype: HTMLVarsomAvalancheEvaluationElement;
        new (): HTMLVarsomAvalancheEvaluationElement;
    };
    interface HTMLVarsomAvalancheEvaluation2Element extends Components.VarsomAvalancheEvaluation2, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvaluation2Element: {
        prototype: HTMLVarsomAvalancheEvaluation2Element;
        new (): HTMLVarsomAvalancheEvaluation2Element;
    };
    interface HTMLVarsomAvalancheEvaluation3Element extends Components.VarsomAvalancheEvaluation3, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheEvaluation3Element: {
        prototype: HTMLVarsomAvalancheEvaluation3Element;
        new (): HTMLVarsomAvalancheEvaluation3Element;
    };
    interface HTMLVarsomAvalancheObsElement extends Components.VarsomAvalancheObs, HTMLStencilElement {
    }
    var HTMLVarsomAvalancheObsElement: {
        prototype: HTMLVarsomAvalancheObsElement;
        new (): HTMLVarsomAvalancheObsElement;
    };
    interface HTMLVarsomCompressionTestElement extends Components.VarsomCompressionTest, HTMLStencilElement {
    }
    var HTMLVarsomCompressionTestElement: {
        prototype: HTMLVarsomCompressionTestElement;
        new (): HTMLVarsomCompressionTestElement;
    };
    interface HTMLVarsomDamageObsElement extends Components.VarsomDamageObs, HTMLStencilElement {
    }
    var HTMLVarsomDamageObsElement: {
        prototype: HTMLVarsomDamageObsElement;
        new (): HTMLVarsomDamageObsElement;
    };
    interface HTMLVarsomDangerObsElement extends Components.VarsomDangerObs, HTMLStencilElement {
    }
    var HTMLVarsomDangerObsElement: {
        prototype: HTMLVarsomDangerObsElement;
        new (): HTMLVarsomDangerObsElement;
    };
    interface HTMLVarsomDocElement extends Components.VarsomDoc, HTMLStencilElement {
    }
    var HTMLVarsomDocElement: {
        prototype: HTMLVarsomDocElement;
        new (): HTMLVarsomDocElement;
    };
    interface HTMLVarsomExposedHeightElement extends Components.VarsomExposedHeight, HTMLStencilElement {
    }
    var HTMLVarsomExposedHeightElement: {
        prototype: HTMLVarsomExposedHeightElement;
        new (): HTMLVarsomExposedHeightElement;
    };
    interface HTMLVarsomGeneralObservationElement extends Components.VarsomGeneralObservation, HTMLStencilElement {
    }
    var HTMLVarsomGeneralObservationElement: {
        prototype: HTMLVarsomGeneralObservationElement;
        new (): HTMLVarsomGeneralObservationElement;
    };
    interface HTMLVarsomHeaderElement extends Components.VarsomHeader, HTMLStencilElement {
    }
    var HTMLVarsomHeaderElement: {
        prototype: HTMLVarsomHeaderElement;
        new (): HTMLVarsomHeaderElement;
    };
    interface HTMLVarsomIceCoverObservationElement extends Components.VarsomIceCoverObservation, HTMLStencilElement {
    }
    var HTMLVarsomIceCoverObservationElement: {
        prototype: HTMLVarsomIceCoverObservationElement;
        new (): HTMLVarsomIceCoverObservationElement;
    };
    interface HTMLVarsomIceThicknessElement extends Components.VarsomIceThickness, HTMLStencilElement {
    }
    var HTMLVarsomIceThicknessElement: {
        prototype: HTMLVarsomIceThicknessElement;
        new (): HTMLVarsomIceThicknessElement;
    };
    interface HTMLVarsomIceThicknessLayerElement extends Components.VarsomIceThicknessLayer, HTMLStencilElement {
    }
    var HTMLVarsomIceThicknessLayerElement: {
        prototype: HTMLVarsomIceThicknessLayerElement;
        new (): HTMLVarsomIceThicknessLayerElement;
    };
    interface HTMLVarsomImageSliderElement extends Components.VarsomImageSlider, HTMLStencilElement {
    }
    var HTMLVarsomImageSliderElement: {
        prototype: HTMLVarsomImageSliderElement;
        new (): HTMLVarsomImageSliderElement;
    };
    interface HTMLVarsomImageSliderMobileElement extends Components.VarsomImageSliderMobile, HTMLStencilElement {
    }
    var HTMLVarsomImageSliderMobileElement: {
        prototype: HTMLVarsomImageSliderMobileElement;
        new (): HTMLVarsomImageSliderMobileElement;
    };
    interface HTMLVarsomIncidentElement extends Components.VarsomIncident, HTMLStencilElement {
    }
    var HTMLVarsomIncidentElement: {
        prototype: HTMLVarsomIncidentElement;
        new (): HTMLVarsomIncidentElement;
    };
    interface HTMLVarsomKeyValueElement extends Components.VarsomKeyValue, HTMLStencilElement {
    }
    var HTMLVarsomKeyValueElement: {
        prototype: HTMLVarsomKeyValueElement;
        new (): HTMLVarsomKeyValueElement;
    };
    interface HTMLVarsomLabelElement extends Components.VarsomLabel, HTMLStencilElement {
    }
    var HTMLVarsomLabelElement: {
        prototype: HTMLVarsomLabelElement;
        new (): HTMLVarsomLabelElement;
    };
    interface HTMLVarsomLabelSmallElement extends Components.VarsomLabelSmall, HTMLStencilElement {
    }
    var HTMLVarsomLabelSmallElement: {
        prototype: HTMLVarsomLabelSmallElement;
        new (): HTMLVarsomLabelSmallElement;
    };
    interface HTMLVarsomLandslideObservationElement extends Components.VarsomLandslideObservation, HTMLStencilElement {
    }
    var HTMLVarsomLandslideObservationElement: {
        prototype: HTMLVarsomLandslideObservationElement;
        new (): HTMLVarsomLandslideObservationElement;
    };
    interface HTMLVarsomMetadataElement extends Components.VarsomMetadata, HTMLStencilElement {
    }
    var HTMLVarsomMetadataElement: {
        prototype: HTMLVarsomMetadataElement;
        new (): HTMLVarsomMetadataElement;
    };
    interface HTMLVarsomObservationElement extends Components.VarsomObservation, HTMLStencilElement {
    }
    var HTMLVarsomObservationElement: {
        prototype: HTMLVarsomObservationElement;
        new (): HTMLVarsomObservationElement;
    };
    interface HTMLVarsomRegobsLinkElement extends Components.VarsomRegobsLink, HTMLStencilElement {
    }
    var HTMLVarsomRegobsLinkElement: {
        prototype: HTMLVarsomRegobsLinkElement;
        new (): HTMLVarsomRegobsLinkElement;
    };
    interface HTMLVarsomSnowCoverObservationElement extends Components.VarsomSnowCoverObservation, HTMLStencilElement {
    }
    var HTMLVarsomSnowCoverObservationElement: {
        prototype: HTMLVarsomSnowCoverObservationElement;
        new (): HTMLVarsomSnowCoverObservationElement;
    };
    interface HTMLVarsomSnowDensityElement extends Components.VarsomSnowDensity, HTMLStencilElement {
    }
    var HTMLVarsomSnowDensityElement: {
        prototype: HTMLVarsomSnowDensityElement;
        new (): HTMLVarsomSnowDensityElement;
    };
    interface HTMLVarsomSnowDensityLayerElement extends Components.VarsomSnowDensityLayer, HTMLStencilElement {
    }
    var HTMLVarsomSnowDensityLayerElement: {
        prototype: HTMLVarsomSnowDensityLayerElement;
        new (): HTMLVarsomSnowDensityLayerElement;
    };
    interface HTMLVarsomSnowProfileElement extends Components.VarsomSnowProfile, HTMLStencilElement {
    }
    var HTMLVarsomSnowProfileElement: {
        prototype: HTMLVarsomSnowProfileElement;
        new (): HTMLVarsomSnowProfileElement;
    };
    interface HTMLVarsomSnowProfile2Element extends Components.VarsomSnowProfile2, HTMLStencilElement {
    }
    var HTMLVarsomSnowProfile2Element: {
        prototype: HTMLVarsomSnowProfile2Element;
        new (): HTMLVarsomSnowProfile2Element;
    };
    interface HTMLVarsomSnowSurfaceObservationElement extends Components.VarsomSnowSurfaceObservation, HTMLStencilElement {
    }
    var HTMLVarsomSnowSurfaceObservationElement: {
        prototype: HTMLVarsomSnowSurfaceObservationElement;
        new (): HTMLVarsomSnowSurfaceObservationElement;
    };
    interface HTMLVarsomSnowTempElement extends Components.VarsomSnowTemp, HTMLStencilElement {
    }
    var HTMLVarsomSnowTempElement: {
        prototype: HTMLVarsomSnowTempElement;
        new (): HTMLVarsomSnowTempElement;
    };
    interface HTMLVarsomSnowTempObsElement extends Components.VarsomSnowTempObs, HTMLStencilElement {
    }
    var HTMLVarsomSnowTempObsElement: {
        prototype: HTMLVarsomSnowTempObsElement;
        new (): HTMLVarsomSnowTempObsElement;
    };
    interface HTMLVarsomStaticMapElement extends Components.VarsomStaticMap, HTMLStencilElement {
    }
    var HTMLVarsomStaticMapElement: {
        prototype: HTMLVarsomStaticMapElement;
        new (): HTMLVarsomStaticMapElement;
    };
    interface HTMLVarsomStratProfileElement extends Components.VarsomStratProfile, HTMLStencilElement {
    }
    var HTMLVarsomStratProfileElement: {
        prototype: HTMLVarsomStratProfileElement;
        new (): HTMLVarsomStratProfileElement;
    };
    interface HTMLVarsomStratProfileLayerElement extends Components.VarsomStratProfileLayer, HTMLStencilElement {
    }
    var HTMLVarsomStratProfileLayerElement: {
        prototype: HTMLVarsomStratProfileLayerElement;
        new (): HTMLVarsomStratProfileLayerElement;
    };
    interface HTMLVarsomUrlElement extends Components.VarsomUrl, HTMLStencilElement {
    }
    var HTMLVarsomUrlElement: {
        prototype: HTMLVarsomUrlElement;
        new (): HTMLVarsomUrlElement;
    };
    interface HTMLVarsomWaterLevelElement extends Components.VarsomWaterLevel, HTMLStencilElement {
    }
    var HTMLVarsomWaterLevelElement: {
        prototype: HTMLVarsomWaterLevelElement;
        new (): HTMLVarsomWaterLevelElement;
    };
    interface HTMLVarsomWaterLevel2Element extends Components.VarsomWaterLevel2, HTMLStencilElement {
    }
    var HTMLVarsomWaterLevel2Element: {
        prototype: HTMLVarsomWaterLevel2Element;
        new (): HTMLVarsomWaterLevel2Element;
    };
    interface HTMLVarsomWaterMeasurementElement extends Components.VarsomWaterMeasurement, HTMLStencilElement {
    }
    var HTMLVarsomWaterMeasurementElement: {
        prototype: HTMLVarsomWaterMeasurementElement;
        new (): HTMLVarsomWaterMeasurementElement;
    };
    interface HTMLVarsomWeatherObservationElement extends Components.VarsomWeatherObservation, HTMLStencilElement {
    }
    var HTMLVarsomWeatherObservationElement: {
        prototype: HTMLVarsomWeatherObservationElement;
        new (): HTMLVarsomWeatherObservationElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "varsom-attachment": HTMLVarsomAttachmentElement;
        "varsom-avalanche-activity-obs": HTMLVarsomAvalancheActivityObsElement;
        "varsom-avalanche-activity-obs2": HTMLVarsomAvalancheActivityObs2Element;
        "varsom-avalanche-danger-obs": HTMLVarsomAvalancheDangerObsElement;
        "varsom-avalanche-eval-problem": HTMLVarsomAvalancheEvalProblemElement;
        "varsom-avalanche-eval-problem2": HTMLVarsomAvalancheEvalProblem2Element;
        "varsom-avalanche-evaluation": HTMLVarsomAvalancheEvaluationElement;
        "varsom-avalanche-evaluation2": HTMLVarsomAvalancheEvaluation2Element;
        "varsom-avalanche-evaluation3": HTMLVarsomAvalancheEvaluation3Element;
        "varsom-avalanche-obs": HTMLVarsomAvalancheObsElement;
        "varsom-compression-test": HTMLVarsomCompressionTestElement;
        "varsom-damage-obs": HTMLVarsomDamageObsElement;
        "varsom-danger-obs": HTMLVarsomDangerObsElement;
        "varsom-doc": HTMLVarsomDocElement;
        "varsom-exposed-height": HTMLVarsomExposedHeightElement;
        "varsom-general-observation": HTMLVarsomGeneralObservationElement;
        "varsom-header": HTMLVarsomHeaderElement;
        "varsom-ice-cover-observation": HTMLVarsomIceCoverObservationElement;
        "varsom-ice-thickness": HTMLVarsomIceThicknessElement;
        "varsom-ice-thickness-layer": HTMLVarsomIceThicknessLayerElement;
        "varsom-image-slider": HTMLVarsomImageSliderElement;
        "varsom-image-slider-mobile": HTMLVarsomImageSliderMobileElement;
        "varsom-incident": HTMLVarsomIncidentElement;
        "varsom-key-value": HTMLVarsomKeyValueElement;
        "varsom-label": HTMLVarsomLabelElement;
        "varsom-label-small": HTMLVarsomLabelSmallElement;
        "varsom-landslide-observation": HTMLVarsomLandslideObservationElement;
        "varsom-metadata": HTMLVarsomMetadataElement;
        "varsom-observation": HTMLVarsomObservationElement;
        "varsom-regobs-link": HTMLVarsomRegobsLinkElement;
        "varsom-snow-cover-observation": HTMLVarsomSnowCoverObservationElement;
        "varsom-snow-density": HTMLVarsomSnowDensityElement;
        "varsom-snow-density-layer": HTMLVarsomSnowDensityLayerElement;
        "varsom-snow-profile": HTMLVarsomSnowProfileElement;
        "varsom-snow-profile2": HTMLVarsomSnowProfile2Element;
        "varsom-snow-surface-observation": HTMLVarsomSnowSurfaceObservationElement;
        "varsom-snow-temp": HTMLVarsomSnowTempElement;
        "varsom-snow-temp-obs": HTMLVarsomSnowTempObsElement;
        "varsom-static-map": HTMLVarsomStaticMapElement;
        "varsom-strat-profile": HTMLVarsomStratProfileElement;
        "varsom-strat-profile-layer": HTMLVarsomStratProfileLayerElement;
        "varsom-url": HTMLVarsomUrlElement;
        "varsom-water-level": HTMLVarsomWaterLevelElement;
        "varsom-water-level2": HTMLVarsomWaterLevel2Element;
        "varsom-water-measurement": HTMLVarsomWaterMeasurementElement;
        "varsom-weather-observation": HTMLVarsomWeatherObservationElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VarsomAttachment {
        "Aspect"?: any;
        "AttachmentId"?: any;
        "AttachmentMimeType"?: any;
        "Comment"?: any;
        "Copyright"?: any;
        "CropImage"?: boolean;
        "GeoHazardName"?: any;
        "GeoHazardTID"?: any;
        "IsMainAttachment"?: any;
        "Photographer"?: any;
        "RegistrationName"?: any;
        "RegistrationTID"?: any;
        "Url"?: any;
    }
    interface VarsomAvalancheActivityObs {
        "Aspect"?: number;
        "Attachments"?: Attachment[];
        "AvalancheActivityObsID"?: number;
        "AvalancheName"?: string;
        "AvalancheTID"?: number;
        "AvalancheTriggerName"?: string;
        "AvalancheTriggerTID"?: number;
        "Comment"?: string;
        "DestructiveSizeName"?: string;
        "DestructiveSizeTID"?: number;
        "DtAvalancheTime"?: string;
        "DtOffAvalancheTime"?: string;
        "EstimatedNumName"?: string;
        "EstimatedNumTID"?: number;
        "HeigthStartZone"?: number;
        "SnowLine"?: number;
        "SnowLineName"?: string;
        "TerrainStartZoneName"?: string;
        "TerrainStartZoneTID"?: number;
        "header"?: string;
        "shortVersion"?: string;
    }
    interface VarsomAvalancheActivityObs2 {
        "Attachments"?: Attachment[];
        "AvalCauseName"?: string;
        "AvalCauseTID"?: number;
        "AvalPropagationName"?: string;
        "AvalPropagationTID"?: number;
        "AvalTriggerSimpleName"?: string;
        "AvalTriggerSimpleTID"?: number;
        "AvalancheExtName"?: string;
        "AvalancheExtTID"?: number;
        "Comment"?: string;
        "DestructiveSizeName"?: string;
        "DestructiveSizeTID"?: number;
        "DtEnd"?: string;
        "DtStart"?: string;
        "EstimatedNumName"?: string;
        "EstimatedNumTID"?: number;
        "ExposedHeight1"?: number;
        "ExposedHeight2"?: number;
        "ExposedHeightComboName"?: string;
        "ExposedHeightComboTID"?: number;
        "ValidExposition"?: string;
        "shortVersion"?: string;
    }
    interface VarsomAvalancheDangerObs {
        "Attachments"?: Attachment[];
        "AvalancheDangerObsID"?: number;
        "Comment"?: string;
        "DangerSignName"?: string;
        "DangerSignTID"?: number;
        "shortVersion"?: string;
    }
    interface VarsomAvalancheEvalProblem {
        "Attachments"?: Attachment[];
        "AvalCauseExtName"?: string;
        "AvalCauseExtTID"?: number;
        "AvalCauseName"?: string;
        "AvalCauseTID"?: number;
        "AvalProbabilityName"?: string;
        "AvalProbabilityTID"?: number;
        "AvalReleaseHeightName"?: string;
        "AvalReleaseHeightTID"?: number;
        "AvalTriggerSimpleName"?: string;
        "AvalTriggerSimpleTID"?: number;
        "AvalancheEvalProblemID"?: number;
        "AvalancheExtName"?: string;
        "AvalancheExtTID"?: number;
        "AvalancheProbabilityAutoText"?: string;
        "AvalancheProblemAutoText"?: string;
        "Comment"?: string;
        "DestructiveSizeExtName"?: string;
        "DestructiveSizeExtTID"?: number;
        "shortVersion"?: string;
    }
    interface VarsomAvalancheEvalProblem2 {
        "Attachments"?: Attachment[];
        "AvalCauseAttributeCrystalName"?: string;
        "AvalCauseAttributeCrystalTID"?: number;
        "AvalCauseAttributeLightName"?: string;
        "AvalCauseAttributeLightTID"?: number;
        "AvalCauseAttributeSoftName"?: string;
        "AvalCauseAttributeSoftTID"?: number;
        "AvalCauseAttributeThinName"?: string;
        "AvalCauseAttributeThinTID"?: number;
        "AvalCauseDepthName"?: string;
        "AvalCauseDepthTID"?: number;
        "AvalCauseName"?: string;
        "AvalCauseTID"?: number;
        "AvalProbabilityName"?: string;
        "AvalProbabilityTID"?: number;
        "AvalPropagationName"?: string;
        "AvalPropagationTID"?: number;
        "AvalTriggerSimpleName"?: string;
        "AvalTriggerSimpleTID"?: number;
        "AvalancheExtName"?: string;
        "AvalancheExtTID"?: number;
        "Comment"?: string;
        "DestructiveSizeName"?: string;
        "DestructiveSizeTID"?: number;
        "ExposedHeight1"?: number;
        "ExposedHeight2"?: number;
        "ExposedHeightComboName"?: string;
        "ExposedHeightComboTID"?: number;
        "ValidExposition"?: string;
        "shortVersion"?: string;
    }
    interface VarsomAvalancheEvaluation {
        "Attachments"?: Attachment[];
        "AvalancheDangerName"?: string;
        "AvalancheDangerTID"?: number;
        "AvalancheEvaluation1"?: string;
        "AvalancheProblemName1"?: string;
        "AvalancheProblemName2"?: string;
        "AvalancheProblemName3"?: string;
        "AvalancheProblemTID1"?: number;
        "AvalancheProblemTID2"?: number;
        "AvalancheProblemTID3"?: number;
        "CanPublish"?: boolean;
        "Comment"?: string;
        "ValidExposition"?: string;
        "ValidHeightFrom"?: number;
        "ValidHeightRelative"?: string;
        "ValidHeigtTo"?: number;
        "shortVersion"?: string;
    }
    interface VarsomAvalancheEvaluation2 {
        "Attachments"?: Attachment[];
        "AvalancheDangerName"?: string;
        "AvalancheDangerTID"?: number;
        "AvalancheDevelopment"?: string;
        "AvalancheEvalProblems"?: AvalancheEvalProblem[];
        "AvalancheEvaluation"?: string;
        "Comment"?: string;
        "ExposedClimateName"?: string;
        "ExposedClimateTID"?: number;
        "ExposedHeight1"?: number;
        "ExposedHeight2"?: number;
        "ExposedHeightComboName"?: string;
        "ExposedHeightComboTID"?: number;
        "ValidExposition"?: string;
        "shortVersion"?: string;
    }
    interface VarsomAvalancheEvaluation3 {
        "Attachments"?: Attachment[];
        "AvalancheDangerName"?: string;
        "AvalancheDangerTID"?: number;
        "AvalancheDevelopment"?: string;
        "AvalancheEvaluation"?: string;
        "ForecastComment"?: string;
        "ForecastCorrectName"?: string;
        "ForecastCorrectTID"?: number;
        "shortVersion"?: string;
    }
    interface VarsomAvalancheObs {
        "Aspect"?: number;
        "Attachments"?: Attachment[];
        "AvalCauseName"?: string;
        "AvalCauseTID"?: number;
        "AvalancheName"?: string;
        "AvalancheTID"?: number;
        "AvalancheTriggerName"?: string;
        "AvalancheTriggerTID"?: number;
        "Comment"?: string;
        "DestructiveSizeName"?: string;
        "DestructiveSizeTID"?: number;
        "DtAvalancheTime"?: string;
        "FractureHeight"?: number;
        "FractureWidth"?: number;
        "HeightStartZone"?: number;
        "HeightStopZone"?: number;
        "Observation"?: Observation;
        "RemotelyTriggered"?: boolean;
        "SnowLine"?: number;
        "StartLat"?: number;
        "StartLong"?: number;
        "StopLat"?: number;
        "StopLong"?: number;
        "TerrainStartZoneName"?: string;
        "TerrainStartZoneTID"?: number;
        "Trajectory"?: string;
        "ValidExposition"?: string;
        "shortVersion"?: string;
    }
    interface VarsomCompressionTest {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "ComprTestFractureName"?: string;
        "ComprTestFractureTID"?: number;
        "CompressionTestName"?: string;
        "CompressionTestTID"?: number;
        "FractureDepth"?: number;
        "IncludeInSnowProfile"?: boolean;
        "PropagationName"?: string;
        "PropagationTID"?: number;
        "PstX"?: number;
        "PstY"?: number;
        "RbRelease"?: number;
        "StabilityEvalName"?: string;
        "StabilityEvalTID"?: number;
        "TapsFracture"?: number;
        "TapsFullPropagation"?: number;
        "shortVersion"?: string;
    }
    interface VarsomDamageObs {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "DamagePosition"?: LatLng;
        "DamageTypeName"?: string;
        "DamageTypeTID"?: number;
        "GeoHazardName"?: string;
        "GeoHazardTID"?: number;
        "shortVersion"?: string;
    }
    interface VarsomDangerObs {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "DangerSignName"?: string;
        "DangerSignTID"?: number;
        "GeoHazardName"?: string;
        "GeoHazardTID"?: number;
        "shortVersion"?: string;
    }
    interface VarsomDoc {
        "Text"?: any;
    }
    interface VarsomExposedHeight {
        "ExposedHeight1"?: any;
        "ExposedHeight2"?: any;
        "ValidExposition"?: any;
    }
    interface VarsomGeneralObservation {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "GeoHazardName"?: string;
        "GeoHazardTID"?: number;
        "ObsComment"?: string;
        "ObsHeader"?: string;
        "Urls"?: Url[];
        "shortVersion"?: string;
    }
    interface VarsomHeader {
        "regId"?: string;
        "region"?: string;
    }
    interface VarsomIceCoverObservation {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "IceCapacityName"?: string;
        "IceCapacityTID"?: number;
        "IceCoverAfterName"?: string;
        "IceCoverAfterTID"?: number;
        "IceCoverBeforeName"?: string;
        "IceCoverBeforeTID"?: number;
        "IceCoverName"?: string;
        "IceCoverTID"?: number;
        "IceSkateabilityName"?: string;
        "IceSkateabilityTID"?: number;
        "shortVersion"?: string;
    }
    interface VarsomIceThickness {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "DtObsTime"?: string;
        "HardCodedImg"?: string;
        "IceHeightAfter"?: number;
        "IceHeightBefore"?: number;
        "IceThicknessLayers"?: IceThicknessLayer[];
        "IceThicknessSum"?: number;
        "LocationName"?: string;
        "ObsLocationId"?: number;
        "SlushSnow"?: number;
        "SnowDepth"?: number;
        "regId"?: number;
        "shortVersion"?: string;
    }
    interface VarsomIceThicknessLayer {
        "Comment"?: string;
        "IceLayerName"?: string;
        "IceLayerThickness"?: number;
        "shortVersion"?: string;
    }
    interface VarsomImageSlider {
        "_images"?: any[];
        "observation"?: Observation;
        "shortVersion"?: string;
    }
    interface VarsomImageSliderMobile {
        "_images"?: any[];
        "observation"?: Observation;
        "shortVersion"?: string;
    }
    interface VarsomIncident {
        "ActivityInfluencedName"?: string;
        "ActivityInfluencedTID"?: number;
        "Attachments"?: Attachment[];
        "CasualtiesNum"?: number;
        "Comment"?: string;
        "DamageExtentName"?: string;
        "DamageExtentTID"?: number;
        "DeadNum"?: number;
        "DtEndTime"?: string;
        "EvacuatedNum"?: number;
        "ForecastAccurateName"?: string;
        "ForecastAccurateTID"?: number;
        "GeoHazardName"?: string;
        "GeoHazardTID"?: number;
        "HarmedNum"?: number;
        "IncidentHeader"?: string;
        "IncidentIngress"?: string;
        "IncidentText"?: string;
        "IncidentURLs"?: Url[];
        "InvolvedNum"?: number;
        "LocalKnowledgeName"?: string;
        "LocalKnowledgeTID"?: number;
        "LocalTouristName"?: string;
        "LocalTouristTID"?: number;
        "MaterialDamages"?: boolean;
        "RescueName"?: string;
        "RescueTID"?: number;
        "SafetyGearName"?: string;
        "SafetyGearTID"?: number;
        "SlopeActivityName"?: string;
        "SlopeActivityTID"?: number;
        "TrafficObstructed"?: boolean;
        "shortVersion"?: string;
    }
    interface VarsomKeyValue {
        "_key"?: string;
        "_value"?: string | number | boolean;
        "shortVersion"?: string;
    }
    interface VarsomLabel {
        "label"?: string;
    }
    interface VarsomLabelSmall {
        "label"?: string;
    }
    interface VarsomLandslideObservation {
        "ActivityInfluencedName"?: string;
        "ActivityInfluencedTID"?: number;
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "DamageExtentName"?: string;
        "DamageExtentTID"?: number;
        "DtLandSlideTime"?: string;
        "DtLandSlideTimeEnd"?: string;
        "ForecastAccurateName"?: string;
        "ForecastAccurateTID"?: number;
        "GeoHazardName"?: string;
        "GeoHazardTID"?: number;
        "LandSlideName"?: string;
        "LandSlideSizeName"?: string;
        "LandSlideSizeTID"?: number;
        "LandSlideTID"?: number;
        "LandSlideTriggerName"?: string;
        "LandSlideTriggerTID"?: number;
        "StartLat"?: number;
        "StartLong"?: number;
        "StopLat"?: number;
        "StopLong"?: number;
        "Urls"?: Url[];
        "shortVersion"?: string;
    }
    interface VarsomMetadata {
        "competenceLevelName"?: string;
        "dateOfLastUpdate"?: string;
        "dateOfObservation"?: string;
        "dateOfRegistration"?: string;
        "geoHazardName"?: string;
        "moh"?: number;
        "nickname"?: string;
        "observerGroupName"?: string;
        "shortVersion"?: string;
    }
    interface VarsomObservation {
        "count"?: number;
        "json"?: any;
        "number"?: number;
        "regid"?: string;
        "type"?: string;
        "version"?: string;
    }
    interface VarsomRegobsLink {
        "regId"?: number;
    }
    interface VarsomSnowCoverObservation {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "CriticalLayerExists"?: boolean;
        "CriticalLayerLocation"?: number;
        "CriticalLayerName"?: string;
        "CriticalLayerTID"?: number;
        "DepthHoarThickness"?: number;
        "SnowPilotRef"?: string;
        "shortVersion"?: string;
    }
    interface VarsomSnowDensity {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "CylinderDiameter"?: number;
        "Density"?: number;
        "Depth"?: number;
        "Layers"?: SnowDensityLayer[];
        "TareWeight"?: number;
        "Weight"?: number;
        "shortVersion"?: string;
    }
    interface VarsomSnowDensityLayer {
        "Density"?: number;
        "Depth"?: number;
        "SortOrder"?: number;
        "Thickness"?: number;
        "WaterEquivalent"?: number;
        "Weight"?: number;
        "shortVersion"?: string;
    }
    interface VarsomSnowProfile {
        "Aspect"?: number;
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "Copyright"?: string;
        "GeoHazardName"?: string;
        "GeoHazardTID"?: number;
        "Photographer"?: string;
        "RegistrationName"?: string;
        "RegistrationTID"?: number;
        "Url"?: string;
        "shortVersion"?: string;
    }
    interface VarsomSnowProfile2 {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "Exposition"?: number;
        "ImageUrl"?: string;
        "IsProfileToGround"?: boolean;
        "RegId"?: number;
        "SlopeAngle"?: number;
        "SnowDensity"?: SnowDensity[];
        "SnowTemp"?: SnowTemp;
        "StratProfile"?: StratProfile;
        "TotalDepth"?: number;
        "Weight"?: number;
        "shortVersion"?: string;
    }
    interface VarsomSnowSurfaceObservation {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "FootPenetration"?: number;
        "HeightLimitLayeredSnow"?: number;
        "NewSnowDepth24"?: number;
        "NewSnowLine"?: number;
        "SkiConditionsName"?: string;
        "SkiConditionsTID"?: number;
        "SnowDepth"?: number;
        "SnowDriftName"?: string;
        "SnowDriftTID"?: number;
        "SnowLine"?: number;
        "SnowSurfaceName"?: string;
        "SnowSurfaceTID"?: number;
        "SurfaceRoughnessName"?: string;
        "SurfaceWaterContentName"?: string;
        "SurfaceWaterContentTID"?: number;
        "shortVersion"?: string;
    }
    interface VarsomSnowTemp {
        "Attachments"?: Attachment[];
        "Layers"?: SnowTempObs[];
        "shortVersion"?: string;
    }
    interface VarsomSnowTempObs {
        "Depth"?: number;
        "SnowTemp"?: number;
        "shortVersion"?: string;
    }
    interface VarsomStaticMap {
        "allowZoom"?: boolean;
        "avalanche"?: boolean;
        "observation"?: Observation;
        "small"?: boolean;
    }
    interface VarsomStratProfile {
        "Attachments"?: Attachment[];
        "Layers"?: StratProfileLayer[];
        "TotalDepth"?: number;
        "shortVersion"?: string;
    }
    interface VarsomStratProfileLayer {
        "Comment"?: string;
        "CriticalLayerTID"?: number;
        "CriticalLayerTName"?: string;
        "DepthTop"?: number;
        "GrainFormPrimaryTID"?: number;
        "GrainFormPrimaryTName"?: string;
        "GrainFormSecondaryTID"?: number;
        "GrainFormSecondaryTName"?: string;
        "GrainSizeAvg"?: number;
        "GrainSizeAvgMax"?: number;
        "HardnessBottomTID"?: number;
        "HardnessBottomTName"?: string;
        "HardnessTID"?: number;
        "HardnessTName"?: string;
        "SortOrder"?: number;
        "Thickness"?: number;
        "WetnessTID"?: number;
        "WetnessTName"?: string;
        "shortVersion"?: string;
    }
    interface VarsomUrl {
        "UrlDescription"?: string;
        "UrlLine"?: string;
    }
    interface VarsomWaterLevel {
        "Attachments"?: Attachment[];
        "IsRiver"?: boolean;
        "MeasuredDischarge"?: number;
        "WaterLevelDescribed"?: number;
        "WaterLevelRefName"?: number;
        "WaterLevelRefTID"?: number;
        "WaterLevelValue"?: number;
        "shortVersion"?: string;
    }
    interface VarsomWaterLevel2 {
        "Attachments"?: Attachment[];
        "Comment"?: string;
        "MarkingReferenceName"?: string;
        "MarkingReferenceTID"?: number;
        "MarkingTypeName"?: string;
        "MarkingTypeTID"?: number;
        "MeasurementReferenceName"?: string;
        "MeasurementReferenceTID"?: number;
        "MeasurementTypeName"?: string;
        "MeasurementTypeTID"?: number;
        "MeasuringToolDescription"?: string;
        "ObservationTimingName"?: string;
        "ObservationTimingTID"?: number;
        "WaterAstrayName"?: string;
        "WaterAstrayTID"?: number;
        "WaterLevelMeasurement"?: WaterLevelMeasurement[];
        "WaterLevelMethodName"?: string;
        "WaterLevelMethodTID"?: number;
        "WaterLevelStateName"?: string;
        "WaterLevelStateTID"?: number;
        "shortVersion"?: string;
    }
    interface VarsomWaterMeasurement {
        "Comment"?: string;
        "DtMeasurementTime"?: string;
        "WaterLevelValue"?: number;
        "shortVersion"?: string;
    }
    interface VarsomWeatherObservation {
        "AirTemperature"?: number;
        "Attachments"?: Attachment[];
        "CloudCover"?: number;
        "Comment"?: string;
        "PrecipitationName"?: string;
        "PrecipitationTID"?: number;
        "WindDirection"?: number;
        "WindDirectionName"?: string;
        "WindSpeed"?: number;
        "shortVersion"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "varsom-attachment": VarsomAttachment;
        "varsom-avalanche-activity-obs": VarsomAvalancheActivityObs;
        "varsom-avalanche-activity-obs2": VarsomAvalancheActivityObs2;
        "varsom-avalanche-danger-obs": VarsomAvalancheDangerObs;
        "varsom-avalanche-eval-problem": VarsomAvalancheEvalProblem;
        "varsom-avalanche-eval-problem2": VarsomAvalancheEvalProblem2;
        "varsom-avalanche-evaluation": VarsomAvalancheEvaluation;
        "varsom-avalanche-evaluation2": VarsomAvalancheEvaluation2;
        "varsom-avalanche-evaluation3": VarsomAvalancheEvaluation3;
        "varsom-avalanche-obs": VarsomAvalancheObs;
        "varsom-compression-test": VarsomCompressionTest;
        "varsom-damage-obs": VarsomDamageObs;
        "varsom-danger-obs": VarsomDangerObs;
        "varsom-doc": VarsomDoc;
        "varsom-exposed-height": VarsomExposedHeight;
        "varsom-general-observation": VarsomGeneralObservation;
        "varsom-header": VarsomHeader;
        "varsom-ice-cover-observation": VarsomIceCoverObservation;
        "varsom-ice-thickness": VarsomIceThickness;
        "varsom-ice-thickness-layer": VarsomIceThicknessLayer;
        "varsom-image-slider": VarsomImageSlider;
        "varsom-image-slider-mobile": VarsomImageSliderMobile;
        "varsom-incident": VarsomIncident;
        "varsom-key-value": VarsomKeyValue;
        "varsom-label": VarsomLabel;
        "varsom-label-small": VarsomLabelSmall;
        "varsom-landslide-observation": VarsomLandslideObservation;
        "varsom-metadata": VarsomMetadata;
        "varsom-observation": VarsomObservation;
        "varsom-regobs-link": VarsomRegobsLink;
        "varsom-snow-cover-observation": VarsomSnowCoverObservation;
        "varsom-snow-density": VarsomSnowDensity;
        "varsom-snow-density-layer": VarsomSnowDensityLayer;
        "varsom-snow-profile": VarsomSnowProfile;
        "varsom-snow-profile2": VarsomSnowProfile2;
        "varsom-snow-surface-observation": VarsomSnowSurfaceObservation;
        "varsom-snow-temp": VarsomSnowTemp;
        "varsom-snow-temp-obs": VarsomSnowTempObs;
        "varsom-static-map": VarsomStaticMap;
        "varsom-strat-profile": VarsomStratProfile;
        "varsom-strat-profile-layer": VarsomStratProfileLayer;
        "varsom-url": VarsomUrl;
        "varsom-water-level": VarsomWaterLevel;
        "varsom-water-level2": VarsomWaterLevel2;
        "varsom-water-measurement": VarsomWaterMeasurement;
        "varsom-weather-observation": VarsomWeatherObservation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "varsom-attachment": LocalJSX.VarsomAttachment & JSXBase.HTMLAttributes<HTMLVarsomAttachmentElement>;
            "varsom-avalanche-activity-obs": LocalJSX.VarsomAvalancheActivityObs & JSXBase.HTMLAttributes<HTMLVarsomAvalancheActivityObsElement>;
            "varsom-avalanche-activity-obs2": LocalJSX.VarsomAvalancheActivityObs2 & JSXBase.HTMLAttributes<HTMLVarsomAvalancheActivityObs2Element>;
            "varsom-avalanche-danger-obs": LocalJSX.VarsomAvalancheDangerObs & JSXBase.HTMLAttributes<HTMLVarsomAvalancheDangerObsElement>;
            "varsom-avalanche-eval-problem": LocalJSX.VarsomAvalancheEvalProblem & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvalProblemElement>;
            "varsom-avalanche-eval-problem2": LocalJSX.VarsomAvalancheEvalProblem2 & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvalProblem2Element>;
            "varsom-avalanche-evaluation": LocalJSX.VarsomAvalancheEvaluation & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvaluationElement>;
            "varsom-avalanche-evaluation2": LocalJSX.VarsomAvalancheEvaluation2 & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvaluation2Element>;
            "varsom-avalanche-evaluation3": LocalJSX.VarsomAvalancheEvaluation3 & JSXBase.HTMLAttributes<HTMLVarsomAvalancheEvaluation3Element>;
            "varsom-avalanche-obs": LocalJSX.VarsomAvalancheObs & JSXBase.HTMLAttributes<HTMLVarsomAvalancheObsElement>;
            "varsom-compression-test": LocalJSX.VarsomCompressionTest & JSXBase.HTMLAttributes<HTMLVarsomCompressionTestElement>;
            "varsom-damage-obs": LocalJSX.VarsomDamageObs & JSXBase.HTMLAttributes<HTMLVarsomDamageObsElement>;
            "varsom-danger-obs": LocalJSX.VarsomDangerObs & JSXBase.HTMLAttributes<HTMLVarsomDangerObsElement>;
            "varsom-doc": LocalJSX.VarsomDoc & JSXBase.HTMLAttributes<HTMLVarsomDocElement>;
            "varsom-exposed-height": LocalJSX.VarsomExposedHeight & JSXBase.HTMLAttributes<HTMLVarsomExposedHeightElement>;
            "varsom-general-observation": LocalJSX.VarsomGeneralObservation & JSXBase.HTMLAttributes<HTMLVarsomGeneralObservationElement>;
            "varsom-header": LocalJSX.VarsomHeader & JSXBase.HTMLAttributes<HTMLVarsomHeaderElement>;
            "varsom-ice-cover-observation": LocalJSX.VarsomIceCoverObservation & JSXBase.HTMLAttributes<HTMLVarsomIceCoverObservationElement>;
            "varsom-ice-thickness": LocalJSX.VarsomIceThickness & JSXBase.HTMLAttributes<HTMLVarsomIceThicknessElement>;
            "varsom-ice-thickness-layer": LocalJSX.VarsomIceThicknessLayer & JSXBase.HTMLAttributes<HTMLVarsomIceThicknessLayerElement>;
            "varsom-image-slider": LocalJSX.VarsomImageSlider & JSXBase.HTMLAttributes<HTMLVarsomImageSliderElement>;
            "varsom-image-slider-mobile": LocalJSX.VarsomImageSliderMobile & JSXBase.HTMLAttributes<HTMLVarsomImageSliderMobileElement>;
            "varsom-incident": LocalJSX.VarsomIncident & JSXBase.HTMLAttributes<HTMLVarsomIncidentElement>;
            "varsom-key-value": LocalJSX.VarsomKeyValue & JSXBase.HTMLAttributes<HTMLVarsomKeyValueElement>;
            "varsom-label": LocalJSX.VarsomLabel & JSXBase.HTMLAttributes<HTMLVarsomLabelElement>;
            "varsom-label-small": LocalJSX.VarsomLabelSmall & JSXBase.HTMLAttributes<HTMLVarsomLabelSmallElement>;
            "varsom-landslide-observation": LocalJSX.VarsomLandslideObservation & JSXBase.HTMLAttributes<HTMLVarsomLandslideObservationElement>;
            "varsom-metadata": LocalJSX.VarsomMetadata & JSXBase.HTMLAttributes<HTMLVarsomMetadataElement>;
            "varsom-observation": LocalJSX.VarsomObservation & JSXBase.HTMLAttributes<HTMLVarsomObservationElement>;
            "varsom-regobs-link": LocalJSX.VarsomRegobsLink & JSXBase.HTMLAttributes<HTMLVarsomRegobsLinkElement>;
            "varsom-snow-cover-observation": LocalJSX.VarsomSnowCoverObservation & JSXBase.HTMLAttributes<HTMLVarsomSnowCoverObservationElement>;
            "varsom-snow-density": LocalJSX.VarsomSnowDensity & JSXBase.HTMLAttributes<HTMLVarsomSnowDensityElement>;
            "varsom-snow-density-layer": LocalJSX.VarsomSnowDensityLayer & JSXBase.HTMLAttributes<HTMLVarsomSnowDensityLayerElement>;
            "varsom-snow-profile": LocalJSX.VarsomSnowProfile & JSXBase.HTMLAttributes<HTMLVarsomSnowProfileElement>;
            "varsom-snow-profile2": LocalJSX.VarsomSnowProfile2 & JSXBase.HTMLAttributes<HTMLVarsomSnowProfile2Element>;
            "varsom-snow-surface-observation": LocalJSX.VarsomSnowSurfaceObservation & JSXBase.HTMLAttributes<HTMLVarsomSnowSurfaceObservationElement>;
            "varsom-snow-temp": LocalJSX.VarsomSnowTemp & JSXBase.HTMLAttributes<HTMLVarsomSnowTempElement>;
            "varsom-snow-temp-obs": LocalJSX.VarsomSnowTempObs & JSXBase.HTMLAttributes<HTMLVarsomSnowTempObsElement>;
            "varsom-static-map": LocalJSX.VarsomStaticMap & JSXBase.HTMLAttributes<HTMLVarsomStaticMapElement>;
            "varsom-strat-profile": LocalJSX.VarsomStratProfile & JSXBase.HTMLAttributes<HTMLVarsomStratProfileElement>;
            "varsom-strat-profile-layer": LocalJSX.VarsomStratProfileLayer & JSXBase.HTMLAttributes<HTMLVarsomStratProfileLayerElement>;
            "varsom-url": LocalJSX.VarsomUrl & JSXBase.HTMLAttributes<HTMLVarsomUrlElement>;
            "varsom-water-level": LocalJSX.VarsomWaterLevel & JSXBase.HTMLAttributes<HTMLVarsomWaterLevelElement>;
            "varsom-water-level2": LocalJSX.VarsomWaterLevel2 & JSXBase.HTMLAttributes<HTMLVarsomWaterLevel2Element>;
            "varsom-water-measurement": LocalJSX.VarsomWaterMeasurement & JSXBase.HTMLAttributes<HTMLVarsomWaterMeasurementElement>;
            "varsom-weather-observation": LocalJSX.VarsomWeatherObservation & JSXBase.HTMLAttributes<HTMLVarsomWeatherObservationElement>;
        }
    }
}
